### 원문 벡터 db + QA 벡터 DB -> 답변 평가 후 -> HyDE 재실행
```
extract_queries → split_queries → tool → qa_tool → basic 
→ evaluate ── good → END
            └─ bad → hyde → tool → qa_tool → basic → evaluate → END
```

In [1]:
from pathlib import Path
import sys

root = Path.cwd()
while not (root / "utils_sec5").exists() and root != root.parent:
    root = root.parent
sys.path.insert(0, str(root))

from utils_sec5.main3 import (run_langraph)

C:\Users\playdata\Documents\1_ai\LLM_hybrid\utils_sec5\retriever.py:51: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-chroma package and should be used instead. To use it run `pip install -U :class:`~langchain-chroma` and import as `from :class:`~langchain_chroma import Chroma``.
  vs = Chroma(

In [2]:
from utils_sec5.langgraph_setting2 import graph_setting

graph = graph_setting()

graph

ValueError: Failed to reach https://mermaid.ink/ API while trying to render your graph. Status code: 502.

To resolve this issue:
1. Check your internet connection and try again
2. Try with higher retry settings: `draw_mermaid_png(..., max_retries=5, retry_delay=2.0)`
3. Use the Pyppeteer rendering method which will render your graph locally in a browser: `draw_mermaid_png(..., draw_method=MermaidDrawMethod.PYPPETEER)`

In [3]:
response = run_langraph('Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?', '1', None)

run_langraph 호출 - 입력: Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['Firebase의 updateTime 필드에 사용되는 시간 형식은 무엇인가요?', "What is the time format used in Firebase's updateTime field?"]
[vector_search_tool] 검색 실행 - query='Firebase의 updateTime 필드에 사용되는 시간 형식은 무엇인가요?', filters={'tags': {'$in': ['firebase_firestore_crawled']}}
[tool_based_search_node] 전달 인자: ['웹 버전 9\nimport { doc, setDoc, Timestamp } from "firebase/firestore";\n\nconst docData = {\nstringExample: "Hello world!",\nbooleanExample: true,\nnumberExample: 3.14159265,\ndateExample: Timestamp.fromDate(new Date("December 10, 1815")),\narrayExample: [5, true, "hello"],\nnullExample: null,\nobjectExample: {\na: 5,\nb: {\nnested: "foo"\n}\n}\n};\nawait setDoc(doc(db, "data", "one"), docData);data_types.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/snippets/firestore-next/test-firestore/data_types.js#L8-L24]\n\n웹 버전 8', 'Web\nimport { updateDoc, serverTimestamp } from "firebase/firestore";\n\nconst docRef = doc(db, \'objects\', \'some-id\');\n\n// Update the timestamp field with the value from the server\nconst updateTimestamp = await updateDoc(docRef, {\ntimestamp: serverTimestamp()\n});update_with_server_timestamp.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/snippets/firestore-next/test-firestore/update_with_server_timestamp.js#L8-L15]\n\nWeb\n\n트리 쉐이킹 작업이 가능한 모듈식 웹 API에 대해 자세히 알아보고 [https://firebase.google.com/docs/web/learn-more?hl=ko#modular-version] 네임스페이스화된 API에 비해 갖는 이점을 살펴보세요.\nvar docRef = db.collection(\'objects\').doc(\'some-id\');\n\n// Update the timestamp field with the value from the server\nvar updateTimestamp = docRef.update({\ntimestamp: firebase.firestore.FieldValue.serverTimestamp()\n});test.firestore.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/firestore/test.firestore.js#L773-L778]\n\nSwift\n\n참고: 이 제품은 watchOS 및 앱 클립 대상에서 사용할 수 없습니다.', '| Fields |\n| --- |\n| name | string The resource name of the Database. Format: projects/{project}/databases/{database} |\n| uid | string Output only. The system-generated UUID4 for this Database. |\n| create_time | Timestamp Output only. The timestamp at which this database was created. Databases created before 2016 do not populate create_time. |\n| update_time | Timestamp Output only. The timestamp at which this database was most recently updated. Note this only includes updates to the database resource and not data contained by the database. |\n| delete_time | Timestamp Output only. The timestamp at which this database was deleted. Only set if the database has been deleted. |\n| location_id | string The location of the database. Available locations are listed at https://cloud.google.com/firestore/docs/locations. |\n| type | DatabaseType The type of the database. See https://cloud.google.com/datastore/docs/firestore-or-datastore for information about how to choose. |\n| concurrency_mode | ConcurrencyMode The concurrency control mode to use for this database. |', '| Fields |\n| --- |\n| name | string The resource name of the Database. Format: projects/{project}/databases/{database} |\n| uid | string Output only. The system-generated UUID4 for this Database. |\n| create_time | Timestamp Output only. The timestamp at which this database was created. Databases created before 2016 do not populate create_time. |\n| update_time | Timestamp Output only. The timestamp at which this database was most recently updated. Note this only includes updates to the database resource and not data contained by the database. |\n| delete_time | Timestamp Output only. The timestamp at which this database was deleted. Only set if the database has been deleted. |\n| location_id | string The location of the database. Available locations are listed at https://cloud.google.com/firestore/docs/locations. |\n| type | DatabaseType The type of the database. See https://cloud.google.com/datastore/docs/firestore-or-datastore for information about how to choose. |\n| concurrency_mode | ConcurrencyMode The concurrency control mode to use for this database. |', '| deleteTime | string (Timestamp format) Output only. The timestamp at which this database was deleted. Only set if the database has been deleted. Uses RFC 3339, where generated output will always be Z-normalized and use 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted. Examples: "2014-10-02T15:01:23Z", "2014-10-02T15:01:23.045123456Z" or "2014-10-02T15:01:23+05:30". |\n| locationId | string The location of the database. Available locations are listed at https://cloud.google.com/firestore/docs/locations. |\n| type | enum (DatabaseType) The type of the database. See https://cloud.google.com/datastore/docs/firestore-or-datastore for information about how to choose. |\n| concurrencyMode | enum (ConcurrencyMode) The concurrency control mode to use for this database. |', '| deleteTime | string (Timestamp format) Output only. The timestamp at which this database was deleted. Only set if the database has been deleted. Uses RFC 3339, where generated output will always be Z-normalized and use 0, 3, 6 or 9 fractional digits. Offsets other than "Z" are also accepted. Examples: "2014-10-02T15:01:23Z", "2014-10-02T15:01:23.045123456Z" or "2014-10-02T15:01:23+05:30". |\n| locationId | string The location of the database. Available locations are listed at https://cloud.google.com/firestore/docs/locations. |\n| type | enum (DatabaseType) The type of the database. See https://cloud.google.com/datastore/docs/firestore-or-datastore for information about how to choose. |\n| concurrencyMode | enum (ConcurrencyMode) The concurrency control mode to use for this database. |', '웹 버전 9\nupdateDoc() 메서드를 사용합니다.\nimport { doc, updateDoc } from "firebase/firestore";\n\nconst washingtonRef = doc(db, "cities", "DC");\n\n// Set the "capital" field of the city \'DC\'\nawait updateDoc(washingtonRef, {\ncapital: true\n});update_document.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/snippets/firestore-next/test-firestore/update_document.js#L8-L15]\n\n웹 버전 8\nupdate() 메서드를 사용합니다.\nvar washingtonRef = db.collection("cities").doc("DC");\n\n// Set the "capital" field of the city \'DC\'\nreturn washingtonRef.update({\ncapital: true\n})\n.then(() => {\nconsole.log("Document successfully updated!");\n})\n.catch((error) => {\n// The document probably doesn\'t exist.\nconsole.error("Error updating document: ", error);\n});test.firestore.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/firestore/test.firestore.js#L467-L479]\n\nSwift\nupdateData() 메서드를 사용합니다.\n\n참고: 이 제품은 watchOS 및 앱 클립 대상에서 사용할 수 없습니다.\n\nlet washingtonRef = db.collection("cities").document("DC")', 'UpdateBackupScheduleRequest\n\nThe request for FirestoreAdmin.UpdateBackupSchedule [https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.UpdateBackupSchedule].\n\n| Fields |\n| --- |\n| backup_schedule | BackupSchedule Required. The backup schedule to update. |\n| update_mask | FieldMask The list of fields to be updated. |\n\nUpdateDatabaseMetadata\nThis type has no fields.\n\nMetadata related to the update database operation.\n\nUpdateDatabaseRequest\n\nThe request for FirestoreAdmin.UpdateDatabase [https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.UpdateDatabase].\n\n| Fields |\n| --- |\n| database | Database Required. The database to update. |\n| update_mask | FieldMask The list of fields to be updated. |\n\nUpdateFieldRequest\n\nThe request for FirestoreAdmin.UpdateField [https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.UpdateField].']
[vector_search_tool] 검색 실행 - query='What is the time format used in Firebase's updateTime field?', filters={'tags': {'$in': ['firebase_firestore_crawled']}}
[tool_based_search_node] 전달 인자: ['Web\nimport { updateDoc, serverTimestamp } from "firebase/firestore";\n\nconst docRef = doc(db, \'objects\', \'some-id\');\n\n// Update the timestamp field with the value from the server\nconst updateTimestamp = await updateDoc(docRef, {\ntimestamp: serverTimestamp()\n});update_with_server_timestamp.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/snippets/firestore-next/test-firestore/update_with_server_timestamp.js#L8-L15]\n\nWeb\n\n트리 쉐이킹 작업이 가능한 모듈식 웹 API에 대해 자세히 알아보고 [https://firebase.google.com/docs/web/learn-more?hl=ko#modular-version] 네임스페이스화된 API에 비해 갖는 이점을 살펴보세요.\nvar docRef = db.collection(\'objects\').doc(\'some-id\');\n\n// Update the timestamp field with the value from the server\nvar updateTimestamp = docRef.update({\ntimestamp: firebase.firestore.FieldValue.serverTimestamp()\n});test.firestore.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/firestore/test.firestore.js#L773-L778]\n\nSwift\n\n참고: 이 제품은 watchOS 및 앱 클립 대상에서 사용할 수 없습니다.', '웹 버전 9\nimport { doc, setDoc, Timestamp } from "firebase/firestore";\n\nconst docData = {\nstringExample: "Hello world!",\nbooleanExample: true,\nnumberExample: 3.14159265,\ndateExample: Timestamp.fromDate(new Date("December 10, 1815")),\narrayExample: [5, true, "hello"],\nnullExample: null,\nobjectExample: {\na: 5,\nb: {\nnested: "foo"\n}\n}\n};\nawait setDoc(doc(db, "data", "one"), docData);data_types.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/snippets/firestore-next/test-firestore/data_types.js#L8-L24]\n\n웹 버전 8', 'UpdateBackupScheduleRequest\n\nThe request for FirestoreAdmin.UpdateBackupSchedule [https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.UpdateBackupSchedule].\n\n| Fields |\n| --- |\n| backup_schedule | BackupSchedule Required. The backup schedule to update. |\n| update_mask | FieldMask The list of fields to be updated. |\n\nUpdateDatabaseMetadata\nThis type has no fields.\n\nMetadata related to the update database operation.\n\nUpdateDatabaseRequest\n\nThe request for FirestoreAdmin.UpdateDatabase [https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.UpdateDatabase].\n\n| Fields |\n| --- |\n| database | Database Required. The database to update. |\n| update_mask | FieldMask The list of fields to be updated. |\n\nUpdateFieldRequest\n\nThe request for FirestoreAdmin.UpdateField [https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.UpdateField].', '| Fields |\n| --- |\n| name | string The resource name of the Database. Format: projects/{project}/databases/{database} |\n| uid | string Output only. The system-generated UUID4 for this Database. |\n| create_time | Timestamp Output only. The timestamp at which this database was created. Databases created before 2016 do not populate create_time. |\n| update_time | Timestamp Output only. The timestamp at which this database was most recently updated. Note this only includes updates to the database resource and not data contained by the database. |\n| delete_time | Timestamp Output only. The timestamp at which this database was deleted. Only set if the database has been deleted. |\n| location_id | string The location of the database. Available locations are listed at https://cloud.google.com/firestore/docs/locations. |\n| type | DatabaseType The type of the database. See https://cloud.google.com/datastore/docs/firestore-or-datastore for information about how to choose. |\n| concurrency_mode | ConcurrencyMode The concurrency control mode to use for this database. |', '| Fields |\n| --- |\n| name | string The resource name of the Database. Format: projects/{project}/databases/{database} |\n| uid | string Output only. The system-generated UUID4 for this Database. |\n| create_time | Timestamp Output only. The timestamp at which this database was created. Databases created before 2016 do not populate create_time. |\n| update_time | Timestamp Output only. The timestamp at which this database was most recently updated. Note this only includes updates to the database resource and not data contained by the database. |\n| delete_time | Timestamp Output only. The timestamp at which this database was deleted. Only set if the database has been deleted. |\n| location_id | string The location of the database. Available locations are listed at https://cloud.google.com/firestore/docs/locations. |\n| type | DatabaseType The type of the database. See https://cloud.google.com/datastore/docs/firestore-or-datastore for information about how to choose. |\n| concurrency_mode | ConcurrencyMode The concurrency control mode to use for this database. |', '웹 버전 9\nupdateDoc() 메서드를 사용합니다.\nimport { doc, updateDoc } from "firebase/firestore";\n\nconst washingtonRef = doc(db, "cities", "DC");\n\n// Set the "capital" field of the city \'DC\'\nawait updateDoc(washingtonRef, {\ncapital: true\n});update_document.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/snippets/firestore-next/test-firestore/update_document.js#L8-L15]\n\n웹 버전 8\nupdate() 메서드를 사용합니다.\nvar washingtonRef = db.collection("cities").doc("DC");\n\n// Set the "capital" field of the city \'DC\'\nreturn washingtonRef.update({\ncapital: true\n})\n.then(() => {\nconsole.log("Document successfully updated!");\n})\n.catch((error) => {\n// The document probably doesn\'t exist.\nconsole.error("Error updating document: ", error);\n});test.firestore.js [https://github.com/firebase/snippets-web/blob/467eaa165dcbd9b3ab15711e76fa52237ba37f8b/firestore/test.firestore.js#L467-L479]\n\nSwift\nupdateData() 메서드를 사용합니다.\n\n참고: 이 제품은 watchOS 및 앱 클립 대상에서 사용할 수 없습니다.\n\nlet washingtonRef = db.collection("cities").document("DC")', 'UpdateBackupScheduleRequest\n\nThe request for FirestoreAdmin.UpdateBackupSchedule [https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.UpdateBackupSchedule].\n\n| Fields |\n| --- |\n| backup_schedule | BackupSchedule Required. The backup schedule to update. |\n| update_mask | FieldMask The list of fields to be updated. |\n\nUpdateDatabaseMetadata\nThis type has no fields.\n\nMetadata related to the update database operation.\n\nUpdateDatabaseRequest\n\nThe request for FirestoreAdmin.UpdateDatabase [https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.UpdateDatabase].\n\n| Fields |\n| --- |\n| database | Database Required. The database to update. |\n| update_mask | FieldMask The list of fields to be updated. |\n\nUpdateFieldRequest\n\nThe request for FirestoreAdmin.UpdateField [https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.UpdateField].', 'Updates a database.\n\nHTTP request\nPATCH https://firestore.googleapis.com/v1/{database.name=projects/*/databases/*}The URL uses gRPC Transcoding [https://google.aip.dev/127] syntax.\n\nPath parameters\n| Parameters |\n| --- |\n| database.name | string The resource name of the Database. Format: projects/{project}/databases/{database} |\n\nQuery parameters\n| Parameters |\n| --- |\n| updateMask | string (FieldMask format) The list of fields to be updated. This is a comma-separated list of fully qualified names of fields. Example: "user.displayName,photo". |\n\nRequest body\nThe request body contains an instance of Database [https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases#Database].\n\nResponse body\nIf successful, the response body contains an instance of Operation [https://cloud.google.com/firestore/docs/reference/rest/Shared.Types/Operation].\n\nAuthorization scopes\nRequires one of the following OAuth scopes:\n\nhttps://www.googleapis.com/auth/datastore\nhttps://www.googleapis.com/auth/cloud-platform\nFor more information, see the Authentication Overview [https://cloud.google.com/docs/authentication#authorization-gcp].\n\n도움이 되었나요?\n\nSend feedback']
[qa_tool_based_search_node] 실행 - queries=['Firebase의 updateTime 필드에 사용되는 시간 형식은 무엇인가요?', "What is the time format used in Firebase's updateTime field?"]
[qa_vector_search_tool] 검색 실행 - query='Firebase의 updateTime 필드에 사용되는 시간 형식은 무엇인가요?', filters={'tags': {'$in': ['firestore', 'firebase_authentication']}}

In [4]:
print(response['answer'])

Firebase의 `updateTime` 필드는 RFC 3339 형식을 사용합니다. 이 형식은 다음과 같은 예시를 포함합니다: "2014-10-02T15:01:23Z", "2014-10-02T15:01:23.045123456Z" 또는 "2014-10-02T15:01:23+05:30". 이 형식은 타임스탬프를 Z-normalized로 표현하며, 0, 3, 6 또는 9의 소수 자릿수를 사용할 수 있습니다.

In [5]:
response = run_langraph('GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?', '1', None)
print(response)

run_langraph 호출 - 입력: GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['GMSMapPoint의 좌표계에서 (0, 0)이 의미하는 지점은 어디인가요?', 'What does the point (0, 0) represent in the GMSMapPoint coordinate system?']
[vector_search_tool] 검색 실행 - query='GMSMapPoint의 좌표계에서 (0, 0)이 의미하는 지점은 어디인가요?', filters={'tags': {'$in': ['map']}}
[tool_based_search_node] 전달 인자: ['GMSProjection [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSProjection]\nDefines a mapping between Earth coordinates CLLocationCoordinate2D and coordinates in the map’s view CGPoint. A projection is constant and immutable, in that the mapping it embodies never changes. The mapping is not necessarily linear.\nPassing invalid Earth coordinates (i.e., per CLLocationCoordinate2DIsValid) to this object may result in undefined behavior.\nThis class should not be instantiated directly unless under testing conditions. Instead, obtain it via projection on GMSMapView [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMapView].\nDeclaration\nSWIFT\nclass GMSProjection : NSObject\nOBJECTIVE-C\n@interface GMSProjection : NSObject\nGMSServices [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSServices]\nService class for the Google Maps SDK for iOS.\nThis class is not thread safe. All methods should only be invoked on the main thread.\nDeclaration\nSWIFT\nclass GMSServices : NSObject\nOBJECTIVE-C\n@interface GMSServices : NSObject', 'Declaration\nSWIFT\nclass GMSMapViewOptions : NSObject\nOBJECTIVE-C\n@interface GMSMapViewOptions : NSObject\nGMSMarker [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSMarker]\nA marker is an icon placed at a particular point on the map’s surface. A marker’s icon is drawn oriented against the device’s screen rather than the map’s surface; i.e., it will not necessarily change orientation due to map rotations, tilting, or zooming.\nDeclaration\nSWIFT\nclass GMSMarker : GMSOverlay [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSOverlay]\nOBJECTIVE-C\n@interface GMSMarker : GMSOverlay [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSOverlay]\nGMSMarkerLayer [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSMarkerLayer]\nGMSMarkerLayer is a subclass of GMSOverlayLayer [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSOverlayLayer], available on a per-marker basis, that allows animation of several properties of its associated GMSMarker [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSMarker].', 'Declaration\nSWIFT\nclass GMSMapStyle : NSObject\nOBJECTIVE-C\n@interface GMSMapStyle : NSObject\nGMSMarker [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMarker]\nA marker is an icon placed at a particular point on the map’s surface. A marker’s icon is drawn oriented against the device’s screen rather than the map’s surface; i.e., it will not necessarily change orientation due to map rotations, tilting, or zooming.\nDeclaration\nSWIFT\nclass GMSMarker : GMSOverlay [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSOverlay]\nOBJECTIVE-C\n@interface GMSMarker : GMSOverlay [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSOverlay]\nGMSMarkerLayer [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMarkerLayer]', '{\n  "snappedPoints":\n    [\n      {\n        "location":\n          { "latitude": -35.27800489993019, "longitude": 149.129531998742 },\n        "originalIndex": 0,\n        "placeId": "ChIJr_xl0GdNFmsRsUtUbW7qABM",\n      },\n      {\n        "location":\n          { "latitude": -35.2784195, "longitude": 149.12946589999999 },\n        "placeId": "ChIJr_xl0GdNFmsRsUtUbW7qABM",\n      },\n      {\n        "location":\n          { "latitude": -35.2784195, "longitude": 149.12946589999999 },\n        "placeId": "ChIJ6aXGemhNFmsRZE_zHqhmrG4",\n      },\n      {\n        "location":\n          { "latitude": -35.2792731, "longitude": 149.12933809999998 },\n        "placeId": "ChIJ6aXGemhNFmsRZE_zHqhmrG4",\n      },\n      {\n        "location":\n          { "latitude": -35.2792731, "longitude": 149.12933809999998 },\n        "placeId": "ChIJTcTdZ2hNFmsRXokM4mWCWfk",\n      },\n      {\n        "location": { "latitude": -35.279557, "longitude": 149.1292973 },\n        "placeId": "ChIJTcTdZ2hNFmsRXokM4mWCWfk",\n      },\n      {\n        "location": { "latitude": -35.279557, "longitude": 149.1292973 },\n        "placeId": "ChIJiUfNQmhNFmsRSsAI-1m6y1g",\n      },\n      {\n        "location":', 'GMSCoordinateBounds in Place Autocomplete (v3.9.0 - v4.0.0)\nSeveral properties andparameters using GMSCoordinateBounds [https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_coordinate_bounds] in the Places SDK for iOS Autocomplete service, are deprecated as of v3.9.0 [https://developers.google.com/maps/documentation/places/ios-sdk/releases#2020-05-26], and are unsupported in v4.0.0 [https://developers.google.com/maps/documentation/places/ios-sdk/releases#2020-10-13] and higher. The maximum supporting version for the deprecated properties and parameters is v3.10.0 [https://developers.google.com/maps/documentation/places/ios-sdk/releases#2020-08-10].\nBounds in GMSAutocompleteViewController\nThe following GMSAutocompleteViewController properties are deprecated:\nGMSAutocompleteViewController.autocompleteBounds [https://developers.google.com/maps/documentation/places/ios-sdk/reference/interface_g_m_s_autocomplete_view_controller#a65482d86732910ff07a2827b6d181dc5]', 'GMSAddress [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSAddress]\nA result from a reverse geocode request, containing a human-readable address. This class is immutable and should not be instantiated directly unless under testing circumstances. Obtain an instance via GMSGeocoder [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSGeocoder].\nSome of the fields may be nil, indicating they are not present.\nDeclaration\nSWIFT\nclass GMSAddress : NSObject, NSCopying, NSSecureCoding\nOBJECTIVE-C\n@interface GMSAddress : NSObject <NSCopying, NSSecureCoding>\nGMSAdvancedMarker [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSAdvancedMarker]\nAn advanced marker is an icon placed at a particular point on the map’s surface.\nDeclaration\nSWIFT\nclass GMSAdvancedMarker : GMSMarker [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMarker]\nOBJECTIVE-C\n@interface GMSAdvancedMarker : GMSMarker [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMarker]', 'GMSCoordinateBounds [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSCoordinateBounds]\nGMSCoordinateBounds represents a rectangular bounding box on the Earth’s surface. GMSCoordinateBounds is immutable and can’t be modified after construction.\nDeclaration\nSWIFT\nclass GMSCoordinateBounds : NSObject\nOBJECTIVE-C\n@interface GMSCoordinateBounds : NSObject\nGMSDatasetFeature [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSDatasetFeature]\nAn interface representing a feature from a dataset.\nThe featureType of a DatasetFeature will always be GMSFeatureTypeDataset [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Constants/GMSFeatureTypeDataset].\nDeclaration\nSWIFT\nclass DatasetFeature : NSObject, Feature\nOBJECTIVE-C\n@interface GMSDatasetFeature : NSObject <GMSFeature [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Protocols/GMSFeature]>\nGMSDatasetFeatureLayer [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSDatasetFeatureLayer]\nAn interface representing a feature layer for a dataset.', '나침반\niOS용 Maps SDK는 특정 상황에서 지도의 오른쪽 상단에 표시되는 나침반 그래픽을 제공합니다. 나침반은 카메라의 방향이 방위가 0이 아닌 상태로 설정되어 있는 경우에만 표시됩니다. 사용자가 나침반을 클릭하면 카메라가 방위가 0인 위치 (기본 방향)로 다시 움직이고 나침반은 바로 사라집니다.\n나침반은 기본적으로 비활성화되어 있습니다. GMSUISettings의 compassButton 속성을 YES로 설정하여 나침반을 사용 설정할 수 있습니다. 하지만 나침반이 항상 표시되도록 설정할 수는 없습니다.\n내 위치 버튼\n내 위치 버튼은 내 위치 버튼이 사용 설정된 경우에만 화면의 오른쪽 하단에 표시됩니다. 사용자가 버튼을 클릭하면 사용자의 위치를 알고 있는 경우 카메라가 사용자의 현재 위치에 초점을 맞추도록 애니메이션이 적용됩니다. GMSUISettings의 myLocationButton 속성을 YES로 설정하여 버튼을 사용 설정할 수 있습니다.\n층 선택기\n실내 지도가 눈에 띄게 표시되면 층 선택기 컨트롤이 화면의 오른쪽 하단에 표시됩니다. 실내 지도가 2개 이상 표시되면 층 선택기는 화면 중앙에 가장 가까운 건물과 관련이 있습니다. 각 건물에는 기본 층이 있으며 선택기가 처음 표시될 때 이 층이 선택됩니다. 선택기에서 다양한 층을 선택할 수 있습니다.\nGMSUISettings의 indoorPicker 속성을 NO로 설정하여 층 선택기 컨트롤을 사용 중지할 수 있습니다.\n지도 동작\nGMSMapView의 속성으로 제공되는 GMSUISettings 클래스의 속성을 설정하여 지도에서 기본 동작을 사용 중지할 수 있습니다. 다음 제스처는 프로그래밍 방식으로 활성화/비활성화할 수 있습니다. 동작을 사용 중지해도 카메라 설정에 대한 프로그래매틱 액세스는 제한되지 않습니다.\nscrollGestures - 스크롤 동작의 사용 설정 또는 사용 중지 여부를 제어합니다. 이 제스처가 활성화된 경우, 사용자가 카메라를 스와이프해서 패닝할 수 있습니다.\nzoomGestures - 확대/축소 동작의 사용 설정 여부를 제어합니다. 사용 설정하면 사용자가 두 번 탭하거나, 두 손가락으로 탭하거나, 핀치하여 카메라를 확대할 수 있습니다. scrollGestures가 사용 설정된 상태에서 두 번 탭하거나 손가락으로 확대/축소하면 카메라가 지정된 지점으로 이동할 수 있습니다.']
[vector_search_tool] 검색 실행 - query='What does the point (0, 0) represent in the GMSMapPoint coordinate system?', filters={'tags': {'$in': ['map']}}
[tool_based_search_node] 전달 인자: ['GMSProjection [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSProjection]\nDefines a mapping between Earth coordinates CLLocationCoordinate2D and coordinates in the map’s view CGPoint. A projection is constant and immutable, in that the mapping it embodies never changes. The mapping is not necessarily linear.\nPassing invalid Earth coordinates (i.e., per CLLocationCoordinate2DIsValid) to this object may result in undefined behavior.\nThis class should not be instantiated directly unless under testing conditions. Instead, obtain it via projection on GMSMapView [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMapView].\nDeclaration\nSWIFT\nclass GMSProjection : NSObject\nOBJECTIVE-C\n@interface GMSProjection : NSObject\nGMSServices [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSServices]\nService class for the Google Maps SDK for iOS.\nThis class is not thread safe. All methods should only be invoked on the main thread.\nDeclaration\nSWIFT\nclass GMSServices : NSObject\nOBJECTIVE-C\n@interface GMSServices : NSObject', 'Declaration\nSWIFT\nclass GMSMapViewOptions : NSObject\nOBJECTIVE-C\n@interface GMSMapViewOptions : NSObject\nGMSMarker [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSMarker]\nA marker is an icon placed at a particular point on the map’s surface. A marker’s icon is drawn oriented against the device’s screen rather than the map’s surface; i.e., it will not necessarily change orientation due to map rotations, tilting, or zooming.\nDeclaration\nSWIFT\nclass GMSMarker : GMSOverlay [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSOverlay]\nOBJECTIVE-C\n@interface GMSMarker : GMSOverlay [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSOverlay]\nGMSMarkerLayer [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSMarkerLayer]\nGMSMarkerLayer is a subclass of GMSOverlayLayer [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSOverlayLayer], available on a per-marker basis, that allows animation of several properties of its associated GMSMarker [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSMarker].', 'GMSCoordinateBounds [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSCoordinateBounds]\nGMSCoordinateBounds represents a rectangular bounding box on the Earth’s surface. GMSCoordinateBounds is immutable and can’t be modified after construction.\nDeclaration\nSWIFT\nclass GMSCoordinateBounds : NSObject\nOBJECTIVE-C\n@interface GMSCoordinateBounds : NSObject\nGMSDatasetFeature [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSDatasetFeature]\nAn interface representing a feature from a dataset.\nThe featureType of a DatasetFeature will always be GMSFeatureTypeDataset [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Constants/GMSFeatureTypeDataset].\nDeclaration\nSWIFT\nclass DatasetFeature : NSObject, Feature\nOBJECTIVE-C\n@interface GMSDatasetFeature : NSObject <GMSFeature [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Protocols/GMSFeature]>\nGMSDatasetFeatureLayer [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSDatasetFeatureLayer]\nAn interface representing a feature layer for a dataset.', 'GMSCoordinateBounds in Place Autocomplete (v3.9.0 - v4.0.0)\nSeveral properties andparameters using GMSCoordinateBounds [https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_coordinate_bounds] in the Places SDK for iOS Autocomplete service, are deprecated as of v3.9.0 [https://developers.google.com/maps/documentation/places/ios-sdk/releases#2020-05-26], and are unsupported in v4.0.0 [https://developers.google.com/maps/documentation/places/ios-sdk/releases#2020-10-13] and higher. The maximum supporting version for the deprecated properties and parameters is v3.10.0 [https://developers.google.com/maps/documentation/places/ios-sdk/releases#2020-08-10].\nBounds in GMSAutocompleteViewController\nThe following GMSAutocompleteViewController properties are deprecated:\nGMSAutocompleteViewController.autocompleteBounds [https://developers.google.com/maps/documentation/places/ios-sdk/reference/interface_g_m_s_autocomplete_view_controller#a65482d86732910ff07a2827b6d181dc5]', '{\n  "snappedPoints":\n    [\n      {\n        "location":\n          { "latitude": -35.27800489993019, "longitude": 149.129531998742 },\n        "originalIndex": 0,\n        "placeId": "ChIJr_xl0GdNFmsRsUtUbW7qABM",\n      },\n      {\n        "location":\n          { "latitude": -35.2784195, "longitude": 149.12946589999999 },\n        "placeId": "ChIJr_xl0GdNFmsRsUtUbW7qABM",\n      },\n      {\n        "location":\n          { "latitude": -35.2784195, "longitude": 149.12946589999999 },\n        "placeId": "ChIJ6aXGemhNFmsRZE_zHqhmrG4",\n      },\n      {\n        "location":\n          { "latitude": -35.2792731, "longitude": 149.12933809999998 },\n        "placeId": "ChIJ6aXGemhNFmsRZE_zHqhmrG4",\n      },\n      {\n        "location":\n          { "latitude": -35.2792731, "longitude": 149.12933809999998 },\n        "placeId": "ChIJTcTdZ2hNFmsRXokM4mWCWfk",\n      },\n      {\n        "location": { "latitude": -35.279557, "longitude": 149.1292973 },\n        "placeId": "ChIJTcTdZ2hNFmsRXokM4mWCWfk",\n      },\n      {\n        "location": { "latitude": -35.279557, "longitude": 149.1292973 },\n        "placeId": "ChIJiUfNQmhNFmsRSsAI-1m6y1g",\n      },\n      {\n        "location":', 'Declaration\nSWIFT\nclass GMSMapStyle : NSObject\nOBJECTIVE-C\n@interface GMSMapStyle : NSObject\nGMSMarker [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMarker]\nA marker is an icon placed at a particular point on the map’s surface. A marker’s icon is drawn oriented against the device’s screen rather than the map’s surface; i.e., it will not necessarily change orientation due to map rotations, tilting, or zooming.\nDeclaration\nSWIFT\nclass GMSMarker : GMSOverlay [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSOverlay]\nOBJECTIVE-C\n@interface GMSMarker : GMSOverlay [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSOverlay]\nGMSMarkerLayer [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMarkerLayer]', 'Passing invalid Earth coordinates (i.e., per CLLocationCoordinate2DIsValid) to this object may result in undefined behavior.\nThis class should not be instantiated directly unless under testing conditions. Instead, obtain it via projection on GMSMapView [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSMapView].\nDeclaration\nSWIFT\nclass GMSProjection : NSObject\nOBJECTIVE-C\n@interface GMSProjection : NSObject\nGMSServices [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSServices]\nService class for the Google Maps SDK for iOS.\nThis class is not thread safe. All methods should only be invoked on the main thread.\nDeclaration\nSWIFT\nclass GMSServices : NSObject\nOBJECTIVE-C\n@interface GMSServices : NSObject\nGMSStampStyle [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSStampStyle]\nThe abstract base class for polyline styles that draw a repeating image over a GMSStyleSpan [https://developers.google.com/maps/documentation/ios-sdk/reference/objc/Classes/GMSStyleSpan].\nDeclaration\nSWIFT\nclass GMSStampStyle : NSObject\nOBJECTIVE-C\n@interface GMSStampStyle : NSObject', 'GMSAddress [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSAddress]\nA result from a reverse geocode request, containing a human-readable address. This class is immutable and should not be instantiated directly unless under testing circumstances. Obtain an instance via GMSGeocoder [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSGeocoder].\nSome of the fields may be nil, indicating they are not present.\nDeclaration\nSWIFT\nclass GMSAddress : NSObject, NSCopying, NSSecureCoding\nOBJECTIVE-C\n@interface GMSAddress : NSObject <NSCopying, NSSecureCoding>\nGMSAdvancedMarker [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSAdvancedMarker]\nAn advanced marker is an icon placed at a particular point on the map’s surface.\nDeclaration\nSWIFT\nclass GMSAdvancedMarker : GMSMarker [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMarker]\nOBJECTIVE-C\n@interface GMSAdvancedMarker : GMSMarker [https://developers.google.com/maps/documentation/navigation/ios-sdk/reference/objc/Classes/GMSMarker]']
[qa_tool_based_search_node] 실행 - queries=['GMSMapPoint의 좌표계에서 (0, 0)이 의미하는 지점은 어디인가요?', 'What does the point (0, 0) represent in the GMSMapPoint coordinate system?']
[qa_vector_search_tool] 검색 실행 - query='GMSMapPoint의 좌표계에서 (0, 0)이 의미하는 지점은 어디인가요?', filters={'tags': {'$in': ['map']}}

In [6]:
print(response['answer'])
# # print(response['tool_calls'])
# print(response['qa_tool_calls'])

죄송하지만, GMSMapPoint의 좌표계에서 (0, 0)이 어떤 지점을 의미하는지에 대한 정보는 제공된 문서에 포함되어 있지 않습니다. 따라서 이 질문에 대한 답변을 제공할 수 없습니다. 다른 질문이 있으시면 말씀해 주세요.

In [7]:
response = run_langraph('MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일에 직접해야 하나요?', '1', None)

run_langraph 호출 - 입력: MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일에 직접해야 하나요?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일을 직접 수정해야 하나요?', 'Do I need to directly modify the config.json file to configure the cover of MAP 3D storytelling?']
[vector_search_tool] 검색 실행 - query='MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일을 직접 수정해야 하나요?', filters={'tags': {'$in': ['map']}}
[tool_based_search_node] 전달 인자: ["downloadJSON 스키마 다운로드 [https://developers.google.com/static/maps/cbms-json-schema.json?hl=ko]\n스타일 편집기 내에서 JSON을 사용하여 지도 스타일을 수정하거나 지도 스타일을 가져오고 내보내는 방법을 알아보려면 클라우드 기반 지도 스타일 지정에 JSON 사용 [https://developers.google.com/maps/documentation/javascript/cloud-customization/json?hl=ko]을 참고하세요.\nJSON 스타일 선언의 예 보기\nJSON 객체\nJSON 스타일 선언은 최상위 객체와 스타일 규칙 배열로 구성됩니다.\n최상위 설정 (선택사항) - backgroundColor, variant과 같은 전역 스타일 설정입니다.\nstyles - 스타일 규칙 객체의 배열로, 다음으로 구성될 수 있습니다.\nid: 이 스타일 수정에서 선택할 지도 지형지물입니다(예: pointOfInterest.recreation.park)에 복사합니다.\ngeometry (선택사항) - 지도 지형지물의 기하학적 요소와 적용할 스타일 규칙입니다 (예: fillColor)에 복사합니다.\nlabel (선택사항) - 지도 지형지물의 텍스트 또는 핀 라벨과 적용할 스타일 규칙입니다 (예: textStrokeColor)에 복사합니다.\n최상위 수준 설정\n다음 표의 속성은 전체 지도 스타일에 적용됩니다.\n속성 유형 설명 예\nbackgroundColor\n문자열 #RRGGBB 16진수 문자열을 사용하여 지도 앱의 배경색을 맞춤설정합니다. 이 설정은 불투명도 변경을 지원하지 않습니다. '#002211'\nvariant\n'light'|'dark' 밝은 모드 또는 어두운 모드를 지정합니다. 지정하지 않으면 기본값은 'light'입니다. 'light'\nmonochrome\n부울 흑백을 사용 설정하려면 지도의 회색 버전에 true를 사용하세요.\ntrue\n스타일 규칙 객체\n이 섹션에서는 styles 배열에서 스타일 규칙 객체를 정의하여 지도 기능을 맞춤설정하는 속성을 설명합니다. 각 스타일 규칙 객체는 다음으로 구성되어야 합니다.\nid 속성입니다.\n연결된 스타일러 속성이 정의된 geometry 또는 label 요소\nid (지도 기능)\nid 속성은 스타일을 지정할 지도 기능을 지정합니다. 속성 이름은 스타일 편집기의 지도 기능 이름의 카멜케이스 버전입니다.", "downloadJSON 스키마 다운로드 [https://developers.google.com/static/maps/cbms-json-schema.json?hl=ko]\n스타일 편집기 내에서 JSON을 사용하여 지도 스타일을 수정하거나 지도 스타일을 가져오고 내보내는 방법을 알아보려면 클라우드 기반 지도 스타일 지정에 JSON 사용 [https://developers.google.com/maps/documentation/maps-static/cloud-customization/json?hl=ko]을 참고하세요.\nJSON 스타일 선언의 예 보기\nJSON 객체\nJSON 스타일 선언은 최상위 객체와 스타일 규칙 배열로 구성됩니다.\n최상위 설정 (선택사항) - backgroundColor, variant과 같은 전역 스타일 설정입니다.\nstyles - 스타일 규칙 객체의 배열로, 다음으로 구성될 수 있습니다.\nid: 이 스타일 수정에서 선택할 지도 지형지물입니다(예: pointOfInterest.recreation.park)에 복사합니다.\ngeometry (선택사항) - 지도 지형지물의 기하학적 요소와 적용할 스타일 규칙입니다 (예: fillColor)에 복사합니다.\nlabel (선택사항) - 지도 지형지물의 텍스트 또는 핀 라벨과 적용할 스타일 규칙입니다 (예: textStrokeColor)에 복사합니다.\n최상위 수준 설정\n다음 표의 속성은 전체 지도 스타일에 적용됩니다.\n속성 유형 설명 예\nbackgroundColor\n문자열 #RRGGBB 16진수 문자열을 사용하여 지도 앱의 배경색을 맞춤설정합니다. 이 설정은 불투명도 변경을 지원하지 않습니다. '#002211'\nvariant\n'light'|'dark' 밝은 모드 또는 어두운 모드를 지정합니다. 지정하지 않으면 기본값은 'light'입니다. 'light'\nmonochrome\n부울 흑백을 사용 설정하려면 지도의 회색 버전에 true를 사용하세요.\ntrue\n스타일 규칙 객체\n이 섹션에서는 styles 배열에서 스타일 규칙 객체를 정의하여 지도 기능을 맞춤설정하는 속성을 설명합니다. 각 스타일 규칙 객체는 다음으로 구성되어야 합니다.\nid 속성입니다.\n연결된 스타일러 속성이 정의된 geometry 또는 label 요소\nid (지도 기능)\nid 속성은 스타일을 지정할 지도 기능을 지정합니다. 속성 이름은 스타일 편집기의 지도 기능 이름의 카멜케이스 버전입니다.", "downloadJSON 스키마 다운로드 [https://developers.google.com/static/maps/cbms-json-schema.json?hl=ko]\n스타일 편집기 내에서 JSON을 사용하여 지도 스타일을 수정하거나 지도 스타일을 가져오고 내보내는 방법을 알아보려면 클라우드 기반 지도 스타일 지정에 JSON 사용 [https://developers.google.com/maps/documentation/ios-sdk/cloud-customization/json?hl=ko]을 참고하세요.\nJSON 스타일 선언의 예 보기\nJSON 객체\nJSON 스타일 선언은 최상위 객체와 스타일 규칙 배열로 구성됩니다.\n최상위 설정 (선택사항) - backgroundColor, variant과 같은 전역 스타일 설정입니다.\nstyles - 스타일 규칙 객체의 배열로, 다음으로 구성될 수 있습니다.\nid: 이 스타일 수정에서 선택할 지도 지형지물입니다(예: pointOfInterest.recreation.park)에 복사합니다.\ngeometry (선택사항) - 지도 지형지물의 기하학적 요소와 적용할 스타일 규칙입니다 (예: fillColor)에 복사합니다.\nlabel (선택사항) - 지도 지형지물의 텍스트 또는 핀 라벨과 적용할 스타일 규칙입니다 (예: textStrokeColor)에 복사합니다.\n최상위 수준 설정\n다음 표의 속성은 전체 지도 스타일에 적용됩니다.\n속성 유형 설명 예\nbackgroundColor\n문자열 #RRGGBB 16진수 문자열을 사용하여 지도 앱의 배경색을 맞춤설정합니다. 이 설정은 불투명도 변경을 지원하지 않습니다. '#002211'\nvariant\n'light'|'dark' 밝은 모드 또는 어두운 모드를 지정합니다. 지정하지 않으면 기본값은 'light'입니다. 'light'\nmonochrome\n부울 흑백을 사용 설정하려면 지도의 회색 버전에 true를 사용하세요.\ntrue\n스타일 규칙 객체\n이 섹션에서는 styles 배열에서 스타일 규칙 객체를 정의하여 지도 기능을 맞춤설정하는 속성을 설명합니다. 각 스타일 규칙 객체는 다음으로 구성되어야 합니다.\nid 속성입니다.\n연결된 스타일러 속성이 정의된 geometry 또는 label 요소\nid (지도 기능)\nid 속성은 스타일을 지정할 지도 기능을 지정합니다. 속성 이름은 스타일 편집기의 지도 기능 이름의 카멜케이스 버전입니다.", '여러 앱에서 동일한 스타일을 업데이트하려면 Google Cloud 콘솔에서 사용할 수 있고 지도 ID [https://developers.google.com/maps/documentation/get-map-id?hl=ko]가 필요한 클라우드 맞춤설정 [https://developers.google.com/maps/documentation/ios-sdk/cloud-customization?hl=ko]을 살펴보세요. 잠재적인 충돌을 방지하려면 동일한 앱에서 클라우드 맞춤설정과 하드코딩된 스타일 지정을 결합하지 마세요.\n실험 단계: 더 풍부한 스타일 지정 환경을 위해 클라우드 기반 지도 스타일 지정과 JSON 스타일 지정 [https://developers.google.com/maps/documentation/ios-sdk/cloud-customization/json?hl=ko]을 사용할 수 있습니다. 이 기능에는 더 광범위한 지도 기능 목록과 함께 외관을 맞춤설정할 수 있는 더 많은 옵션이 있습니다.\n예\n다음 JSON 스타일 선언에서는 모든 지도 지형지물을 회색으로 바꾸고 간선도로 도형을 파란색으로 칠하며 풍경 라벨을 완전히 숨깁니다.\n[\n  {\n    "featureType": "all",\n    "stylers": [\n      { "color": "#C0C0C0" }\n    ]\n  },{\n    "featureType": "road.arterial",\n    "elementType": "geometry",\n    "stylers": [\n      { "color": "#CCFFFF" }\n    ]\n  },{\n    "featureType": "landscape",\n    "elementType": "labels",\n    "stylers": [\n      { "visibility": "off" }\n    ]\n  }\n]\nJSON 객체\nJSON 스타일 선언은 다음 요소로 구성됩니다.\nfeatureType(선택사항): 이 스타일 변경에서 선택할 지형지물을 나타냅니다. 지형지물은 지도상의 지리적 특성이며 여기에는 도로, 공원, 호수/바다 등이 포함됩니다. 지형지물을 지정하지 않으면 모든 지형지물이 선택됩니다.\nelementType(선택사항): 지정된 지형지물의 속성을 선택할 수 있습니다. 요소는 지형지물의 하위 부분이며 라벨과 도형을 포함합니다. 요소를 지정하지 않으면 지형지물의 모든 요소가 선택됩니다.', '여러 앱에서 동일한 스타일을 업데이트하려면 Google Cloud 콘솔에서 사용할 수 있고 지도 ID [https://developers.google.com/maps/documentation/get-map-id?hl=ko]가 필요한 클라우드 맞춤설정 [https://developers.google.com/maps/documentation/javascript/cloud-customization?hl=ko]을 살펴보세요. 잠재적인 충돌을 방지하려면 동일한 앱에서 클라우드 맞춤설정과 하드코딩된 스타일 지정을 결합하지 마세요.\n실험 단계: 더 풍부한 스타일 지정 환경을 위해 클라우드 기반 지도 스타일 지정과 JSON 스타일 지정 [https://developers.google.com/maps/documentation/javascript/cloud-customization/json?hl=ko]을 사용할 수 있습니다. 이 기능에는 더 광범위한 지도 기능 목록과 함께 외관을 맞춤설정할 수 있는 더 많은 옵션이 있습니다.\n예\n다음 JSON 스타일 선언에서는 모든 지도 지형지물을 회색으로 바꾸고 간선도로 도형을 파란색으로 칠하며 풍경 라벨을 완전히 숨깁니다.\n[\n  {\n    "featureType": "all",\n    "stylers": [\n      { "color": "#C0C0C0" }\n    ]\n  },{\n    "featureType": "road.arterial",\n    "elementType": "geometry",\n    "stylers": [\n      { "color": "#CCFFFF" }\n    ]\n  },{\n    "featureType": "landscape",\n    "elementType": "labels",\n    "stylers": [\n      { "visibility": "off" }\n    ]\n  }\n]\nJSON 객체\nJSON 스타일 선언은 다음 요소로 구성됩니다.\nfeatureType(선택사항): 이 스타일 변경에서 선택할 지형지물을 나타냅니다. 지형지물은 지도상의 지리적 특성이며 여기에는 도로, 공원, 호수/바다 등이 포함됩니다. 지형지물을 지정하지 않으면 모든 지형지물이 선택됩니다.\nelementType(선택사항): 지정된 지형지물의 속성을 선택할 수 있습니다. 요소는 지형지물의 하위 부분이며 라벨과 도형을 포함합니다. 요소를 지정하지 않으면 지형지물의 모든 요소가 선택됩니다.', '여러 앱에서 동일한 스타일을 쉽게 업데이트하려면 Google Cloud 콘솔에서 사용할 수 있는 클라우드 맞춤설정 [https://developers.google.com/maps/documentation/cloud-customization/overview?hl=ko]을 살펴보세요. 클라우드 맞춤설정을 사용하려면 지도 ID [https://developers.google.com/maps/documentation/get-map-id?hl=ko]를 만들고 추가해야 합니다. 향후 발생할 수 있는 충돌을 방지하기 위해 동일한 앱에서 클라우드 맞춤설정 및 하드코딩된 스타일을 결합하지 않는 것이 좋습니다.\n예\n다음 JSON 스타일 선언에서는 모든 지도 지형지물을 회색으로 바꾸고 간선도로 도형을 파란색으로 칠하며 풍경 라벨을 완전히 숨깁니다.\n[\n  {\n    "featureType": "all",\n    "stylers": [\n      { "color": "#C0C0C0" }\n    ]\n  },{\n    "featureType": "road.arterial",\n    "elementType": "geometry",\n    "stylers": [\n      { "color": "#CCFFFF" }\n    ]\n  },{\n    "featureType": "landscape",\n    "elementType": "labels",\n    "stylers": [\n      { "visibility": "off" }\n    ]\n  }\n]\nJSON 객체\nJSON 스타일 선언은 다음 요소로 구성됩니다.\nfeatureType(선택사항): 이 스타일 변경에서 선택할 지형지물을 나타냅니다. 지형지물은 지도상의 지리적 특성이며 여기에는 도로, 공원, 호수/바다 등이 포함됩니다. 지형지물을 지정하지 않으면 모든 지형지물이 선택됩니다.\nelementType(선택사항): 지정된 지형지물의 속성을 선택할 수 있습니다. 요소는 지형지물의 하위 부분이며 라벨과 도형을 포함합니다. 요소를 지정하지 않으면 지형지물의 모든 요소가 선택됩니다.\nstylers: 선택한 지형지물과 요소에 적용할 규칙입니다. 스타일러는 지형지물의 색상, 가시성 및 가중치를 나타냅니다. 하나의 지형지물에 하나 이상의 스타일러를 적용할 수 있습니다.', '이 페이지는 Cloud Translation API [https://cloud.google.com/translate/?hl=ko]를 통해 번역되었습니다.\n홈 [https://developers.google.com/?hl=ko]\n제품 [https://developers.google.com/products?hl=ko]\nGoogle Maps Platform [https://developers.google.com/maps?hl=ko]\n문서 [https://developers.google.com/maps/documentation?hl=ko]\nWeb [https://developers.google.com/maps/web?hl=ko]\nMaps JavaScript API [https://developers.google.com/maps/documentation/javascript?hl=ko]\n의견 보내기\n삽입된 JSON 스타일 선언 사용\n플랫폼 선택: Android [https://developers.google.com/maps/documentation/android-sdk/styling?hl=ko] iOS [https://developers.google.com/maps/documentation/ios-sdk/styling?hl=ko] JavaScript [https://developers.google.com/maps/documentation/javascript/json-styling-overview?hl=ko]\n삽입된 JSON 스타일 선언을 통해 맞춤설정된 스타일을 다음 항목에 적용할 수 있습니다.\n기본 지도\n사용자가 단일 지도 프레임 내에서 전환할 수 있는 지도 유형\n여러 앱에서 동일한 스타일을 업데이트하려면 Google Cloud 콘솔에서 사용할 수 있고 지도 ID [https://developers.google.com/maps/documentation/get-map-id?hl=ko]가 필요한 클라우드 맞춤설정 [https://developers.google.com/maps/documentation/javascript/cloud-customization?hl=ko]을 살펴보세요. 잠재적인 충돌을 방지하려면 동일한 앱에서 클라우드 맞춤설정과 하드코딩된 스타일 지정을 결합하지 마세요.', '지도 ID를 삭제하고 JSON 스타일 지정 [https://developers.google.com/maps/documentation/javascript/json-styling-overview?hl=ko]을 사용하여 각 앱 플랫폼의 스타일을 수정합니다. JSON 스타일 지정은 플랫폼에 따라 다르므로 스타일이 지정된 지도를 표시하는 각 앱 플랫폼에 대해 스타일을 만들어야 합니다.\n클라우드 기반 지도 스타일 지정에 사용할 JSON 지도 스타일이 이미 있는 경우 가져올 수 있습니다. 자세한 내용은 JSON 지도 스타일 가져오기 [https://developers.google.com/maps/documentation/javascript/cloud-customization/map-styles?hl=ko#json-import]를 참고하세요.\n의견 보내기']
[vector_search_tool] 검색 실행 - query='Do I need to directly modify the config.json file to configure the cover of MAP 3D storytelling?', filters={'tags': {'$in': ['map']}}
[tool_based_search_node] 전달 인자: ['assignment [https://developers.google.com/maps/architecture/3d-storytelling-customizations?hl=ko]\n맞춤설정 가이드 [https://developers.google.com/maps/architecture/3d-storytelling-customizations?hl=ko]\n3D 스토리텔링 솔루션은 고도로 맞춤설정할 수 있습니다. 이 가이드 [https://developers.google.com/maps/architecture/3d-storytelling-customizations?hl=ko]에서는 요구사항을 정확히 충족하도록 3D 스토리텔링 솔루션을 맞춤설정하여 매력적인 위치정보 스토리를 만드는 다양한 방법을 안내합니다.\nGitHub에서 코드 보기 [https://github.com/googlemaps-samples/js-3d-storytelling]\n앱을 다운로드하고 맞춤설정합니다.\n소스 코드 보기 [https://github.com/googlemaps-samples/js-3d-storytelling]\n뉴욕 첼시의 이야기 살펴보기 [https://js-3d-storytelling-t6a6o7lkja-uc.a.run.app/]\n풍부한 세부정보를 담은 뉴욕 첼시 지역의 이야기를 3D로 확인하세요\n첼시 스토리pin_drop [https://js-3d-storytelling-t6a6o7lkja-uc.a.run.app/]\n문제 신고 [https://github.com/googlemaps-samples/js-3d-storytelling/issues]\nGitHub Issue Tracker를 사용하여 기능 요청을 제출하거나 버그를 신고하세요.\n문제 제출하기bug_report [https://github.com/googlemaps-samples/js-3d-storytelling/issues]\n[https://goo.gle/3d-storytelling-admin]\n관리 앱 [https://goo.gle/3d-storytelling-admin]\n이 웹 애플리케이션은 3D 환경을 맞춤설정할 수 있는 사용자 친화적인 인터페이스를 제공합니다.\n3D 스토리텔링 환경을 만들고 수정할 수 있는 간편한 인터페이스입니다.\nimageUrl, title, date 등의 기본 속성을 수정하는 전용 구성 패널을 제공합니다.', '이 웹 애플리케이션은 3D 환경을 맞춤설정할 수 있는 사용자 친화적인 인터페이스를 제공합니다.\n3D 스토리텔링 환경을 만들고 수정할 수 있는 간편한 인터페이스입니다.\nimageUrl, title, date 등의 기본 속성을 수정하는 전용 구성 패널을 제공합니다.\n사용자가 각 챕터의 카메라 설정과 포커스 옵션을 미세 조정할 수 있습니다.\n추가 맞춤설정을 위해 생성된 JSON 파일을 다운로드할 수 있는 유연성을 제공합니다.\n관리 앱 보기 [https://goo.gle/3d-storytelling-admin]', '이 페이지는 Cloud Translation API [https://cloud.google.com/translate/?hl=ko]를 통해 번역되었습니다.\n[https://goo.gle/3d-storytelling-admin]\n3D 스토리텔링 [https://goo.gle/3d-storytelling-admin]\n3D 스토리텔링 솔루션은 스토리텔링과 매핑을 연결하므로 크리에이터는 Photorealistic 3D Tiles를 사용하여 몰입도 높은 대화형 내러티브를 만들 수 있습니다.\n앱 둘러보기 [https://goo.gle/3d-storytelling-admin]\n리소스\nstart [https://developers.google.com/maps/architecture/3d-storytelling-getting-started?hl=ko]\n시작하기 [https://developers.google.com/maps/architecture/3d-storytelling-getting-started?hl=ko]\n이 가이드 [https://developers.google.com/maps/architecture/3d-storytelling-getting-started?hl=ko]에서는 3D 스토리텔링 솔루션의 작동 방식, 다양한 구성요소, 배포 및 사용 방법을 간략하게 설명합니다.\nassignment [https://developers.google.com/maps/architecture/3d-storytelling-customizations?hl=ko]\n편집기 사용 방법 [https://developers.google.com/maps/architecture/3d-storytelling-customizations?hl=ko]\n3D 스토리텔링 솔루션에는 스토리를 구성하는 데 도움이 되는 강력한 편집기가 함께 제공됩니다. 이 가이드 [https://developers.google.com/maps/architecture/3d-storytelling-editor?hl=ko]에서는 요구사항을 정확히 충족하도록 3D 스토리텔링 솔루션을 맞춤설정하여 매력적인 위치정보 스토리를 만들 수 있는 다양한 방법을 안내합니다.\nassignment [https://developers.google.com/maps/architecture/3d-storytelling-customizations?hl=ko]', '여러 앱에서 동일한 스타일을 업데이트하려면 Google Cloud 콘솔에서 사용할 수 있고 지도 ID [https://developers.google.com/maps/documentation/get-map-id?hl=ko]가 필요한 클라우드 맞춤설정 [https://developers.google.com/maps/documentation/javascript/cloud-customization?hl=ko]을 살펴보세요. 잠재적인 충돌을 방지하려면 동일한 앱에서 클라우드 맞춤설정과 하드코딩된 스타일 지정을 결합하지 마세요.\n실험 단계: 더 풍부한 스타일 지정 환경을 위해 클라우드 기반 지도 스타일 지정과 JSON 스타일 지정 [https://developers.google.com/maps/documentation/javascript/cloud-customization/json?hl=ko]을 사용할 수 있습니다. 이 기능에는 더 광범위한 지도 기능 목록과 함께 외관을 맞춤설정할 수 있는 더 많은 옵션이 있습니다.\n예\n다음 JSON 스타일 선언에서는 모든 지도 지형지물을 회색으로 바꾸고 간선도로 도형을 파란색으로 칠하며 풍경 라벨을 완전히 숨깁니다.\n[\n  {\n    "featureType": "all",\n    "stylers": [\n      { "color": "#C0C0C0" }\n    ]\n  },{\n    "featureType": "road.arterial",\n    "elementType": "geometry",\n    "stylers": [\n      { "color": "#CCFFFF" }\n    ]\n  },{\n    "featureType": "landscape",\n    "elementType": "labels",\n    "stylers": [\n      { "visibility": "off" }\n    ]\n  }\n]\nJSON 객체\nJSON 스타일 선언은 다음 요소로 구성됩니다.\nfeatureType(선택사항): 이 스타일 변경에서 선택할 지형지물을 나타냅니다. 지형지물은 지도상의 지리적 특성이며 여기에는 도로, 공원, 호수/바다 등이 포함됩니다. 지형지물을 지정하지 않으면 모든 지형지물이 선택됩니다.\nelementType(선택사항): 지정된 지형지물의 속성을 선택할 수 있습니다. 요소는 지형지물의 하위 부분이며 라벨과 도형을 포함합니다. 요소를 지정하지 않으면 지형지물의 모든 요소가 선택됩니다.', '여러 앱에서 동일한 스타일을 업데이트하려면 Google Cloud 콘솔에서 사용할 수 있고 지도 ID [https://developers.google.com/maps/documentation/get-map-id?hl=ko]가 필요한 클라우드 맞춤설정 [https://developers.google.com/maps/documentation/ios-sdk/cloud-customization?hl=ko]을 살펴보세요. 잠재적인 충돌을 방지하려면 동일한 앱에서 클라우드 맞춤설정과 하드코딩된 스타일 지정을 결합하지 마세요.\n실험 단계: 더 풍부한 스타일 지정 환경을 위해 클라우드 기반 지도 스타일 지정과 JSON 스타일 지정 [https://developers.google.com/maps/documentation/ios-sdk/cloud-customization/json?hl=ko]을 사용할 수 있습니다. 이 기능에는 더 광범위한 지도 기능 목록과 함께 외관을 맞춤설정할 수 있는 더 많은 옵션이 있습니다.\n예\n다음 JSON 스타일 선언에서는 모든 지도 지형지물을 회색으로 바꾸고 간선도로 도형을 파란색으로 칠하며 풍경 라벨을 완전히 숨깁니다.\n[\n  {\n    "featureType": "all",\n    "stylers": [\n      { "color": "#C0C0C0" }\n    ]\n  },{\n    "featureType": "road.arterial",\n    "elementType": "geometry",\n    "stylers": [\n      { "color": "#CCFFFF" }\n    ]\n  },{\n    "featureType": "landscape",\n    "elementType": "labels",\n    "stylers": [\n      { "visibility": "off" }\n    ]\n  }\n]\nJSON 객체\nJSON 스타일 선언은 다음 요소로 구성됩니다.\nfeatureType(선택사항): 이 스타일 변경에서 선택할 지형지물을 나타냅니다. 지형지물은 지도상의 지리적 특성이며 여기에는 도로, 공원, 호수/바다 등이 포함됩니다. 지형지물을 지정하지 않으면 모든 지형지물이 선택됩니다.\nelementType(선택사항): 지정된 지형지물의 속성을 선택할 수 있습니다. 요소는 지형지물의 하위 부분이며 라벨과 도형을 포함합니다. 요소를 지정하지 않으면 지형지물의 모든 요소가 선택됩니다.', '여러 앱에서 동일한 스타일을 쉽게 업데이트하려면 Google Cloud 콘솔에서 사용할 수 있는 클라우드 맞춤설정 [https://developers.google.com/maps/documentation/cloud-customization/overview?hl=ko]을 살펴보세요. 클라우드 맞춤설정을 사용하려면 지도 ID [https://developers.google.com/maps/documentation/get-map-id?hl=ko]를 만들고 추가해야 합니다. 향후 발생할 수 있는 충돌을 방지하기 위해 동일한 앱에서 클라우드 맞춤설정 및 하드코딩된 스타일을 결합하지 않는 것이 좋습니다.\n예\n다음 JSON 스타일 선언에서는 모든 지도 지형지물을 회색으로 바꾸고 간선도로 도형을 파란색으로 칠하며 풍경 라벨을 완전히 숨깁니다.\n[\n  {\n    "featureType": "all",\n    "stylers": [\n      { "color": "#C0C0C0" }\n    ]\n  },{\n    "featureType": "road.arterial",\n    "elementType": "geometry",\n    "stylers": [\n      { "color": "#CCFFFF" }\n    ]\n  },{\n    "featureType": "landscape",\n    "elementType": "labels",\n    "stylers": [\n      { "visibility": "off" }\n    ]\n  }\n]\nJSON 객체\nJSON 스타일 선언은 다음 요소로 구성됩니다.\nfeatureType(선택사항): 이 스타일 변경에서 선택할 지형지물을 나타냅니다. 지형지물은 지도상의 지리적 특성이며 여기에는 도로, 공원, 호수/바다 등이 포함됩니다. 지형지물을 지정하지 않으면 모든 지형지물이 선택됩니다.\nelementType(선택사항): 지정된 지형지물의 속성을 선택할 수 있습니다. 요소는 지형지물의 하위 부분이며 라벨과 도형을 포함합니다. 요소를 지정하지 않으면 지형지물의 모든 요소가 선택됩니다.\nstylers: 선택한 지형지물과 요소에 적용할 규칙입니다. 스타일러는 지형지물의 색상, 가시성 및 가중치를 나타냅니다. 하나의 지형지물에 하나 이상의 스타일러를 적용할 수 있습니다.', "downloadJSON 스키마 다운로드 [https://developers.google.com/static/maps/cbms-json-schema.json?hl=ko]\n스타일 편집기 내에서 JSON을 사용하여 지도 스타일을 수정하거나 지도 스타일을 가져오고 내보내는 방법을 알아보려면 클라우드 기반 지도 스타일 지정에 JSON 사용 [https://developers.google.com/maps/documentation/javascript/cloud-customization/json?hl=ko]을 참고하세요.\nJSON 스타일 선언의 예 보기\nJSON 객체\nJSON 스타일 선언은 최상위 객체와 스타일 규칙 배열로 구성됩니다.\n최상위 설정 (선택사항) - backgroundColor, variant과 같은 전역 스타일 설정입니다.\nstyles - 스타일 규칙 객체의 배열로, 다음으로 구성될 수 있습니다.\nid: 이 스타일 수정에서 선택할 지도 지형지물입니다(예: pointOfInterest.recreation.park)에 복사합니다.\ngeometry (선택사항) - 지도 지형지물의 기하학적 요소와 적용할 스타일 규칙입니다 (예: fillColor)에 복사합니다.\nlabel (선택사항) - 지도 지형지물의 텍스트 또는 핀 라벨과 적용할 스타일 규칙입니다 (예: textStrokeColor)에 복사합니다.\n최상위 수준 설정\n다음 표의 속성은 전체 지도 스타일에 적용됩니다.\n속성 유형 설명 예\nbackgroundColor\n문자열 #RRGGBB 16진수 문자열을 사용하여 지도 앱의 배경색을 맞춤설정합니다. 이 설정은 불투명도 변경을 지원하지 않습니다. '#002211'\nvariant\n'light'|'dark' 밝은 모드 또는 어두운 모드를 지정합니다. 지정하지 않으면 기본값은 'light'입니다. 'light'\nmonochrome\n부울 흑백을 사용 설정하려면 지도의 회색 버전에 true를 사용하세요.\ntrue\n스타일 규칙 객체\n이 섹션에서는 styles 배열에서 스타일 규칙 객체를 정의하여 지도 기능을 맞춤설정하는 속성을 설명합니다. 각 스타일 규칙 객체는 다음으로 구성되어야 합니다.\nid 속성입니다.\n연결된 스타일러 속성이 정의된 geometry 또는 label 요소\nid (지도 기능)\nid 속성은 스타일을 지정할 지도 기능을 지정합니다. 속성 이름은 스타일 편집기의 지도 기능 이름의 카멜케이스 버전입니다.", "downloadJSON 스키마 다운로드 [https://developers.google.com/static/maps/cbms-json-schema.json?hl=ko]\n스타일 편집기 내에서 JSON을 사용하여 지도 스타일을 수정하거나 지도 스타일을 가져오고 내보내는 방법을 알아보려면 클라우드 기반 지도 스타일 지정에 JSON 사용 [https://developers.google.com/maps/documentation/ios-sdk/cloud-customization/json?hl=ko]을 참고하세요.\nJSON 스타일 선언의 예 보기\nJSON 객체\nJSON 스타일 선언은 최상위 객체와 스타일 규칙 배열로 구성됩니다.\n최상위 설정 (선택사항) - backgroundColor, variant과 같은 전역 스타일 설정입니다.\nstyles - 스타일 규칙 객체의 배열로, 다음으로 구성될 수 있습니다.\nid: 이 스타일 수정에서 선택할 지도 지형지물입니다(예: pointOfInterest.recreation.park)에 복사합니다.\ngeometry (선택사항) - 지도 지형지물의 기하학적 요소와 적용할 스타일 규칙입니다 (예: fillColor)에 복사합니다.\nlabel (선택사항) - 지도 지형지물의 텍스트 또는 핀 라벨과 적용할 스타일 규칙입니다 (예: textStrokeColor)에 복사합니다.\n최상위 수준 설정\n다음 표의 속성은 전체 지도 스타일에 적용됩니다.\n속성 유형 설명 예\nbackgroundColor\n문자열 #RRGGBB 16진수 문자열을 사용하여 지도 앱의 배경색을 맞춤설정합니다. 이 설정은 불투명도 변경을 지원하지 않습니다. '#002211'\nvariant\n'light'|'dark' 밝은 모드 또는 어두운 모드를 지정합니다. 지정하지 않으면 기본값은 'light'입니다. 'light'\nmonochrome\n부울 흑백을 사용 설정하려면 지도의 회색 버전에 true를 사용하세요.\ntrue\n스타일 규칙 객체\n이 섹션에서는 styles 배열에서 스타일 규칙 객체를 정의하여 지도 기능을 맞춤설정하는 속성을 설명합니다. 각 스타일 규칙 객체는 다음으로 구성되어야 합니다.\nid 속성입니다.\n연결된 스타일러 속성이 정의된 geometry 또는 label 요소\nid (지도 기능)\nid 속성은 스타일을 지정할 지도 기능을 지정합니다. 속성 이름은 스타일 편집기의 지도 기능 이름의 카멜케이스 버전입니다."]
[qa_tool_based_search_node] 실행 - queries=['MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일을 직접 수정해야 하나요?', 'Do I need to directly modify the config.json file to configure the cover of MAP 3D storytelling?']
[qa_vector_search_tool] 검색 실행 - query='MAP 3D 스토리텔링의 표지를 구성하기 위해 config.json 파일을 직접 수정해야 하나요?', filters={'tags': {'$in': ['map']}}

In [8]:
print(response['answer'])

3D 스토리텔링 솔루션의 표지를 구성하기 위해 config.json 파일을 직접 수정할 필요는 없습니다. 3D 스토리텔링 솔루션은 사용자 친화적인 인터페이스를 제공하여 imageUrl, title, date 등의 기본 속성을 수정할 수 있는 전용 구성 패널을 제공합니다. 이를 통해 사용자는 각 챕터의 카메라 설정과 포커스 옵션을 미세 조정할 수 있으며, 추가 맞춤설정을 위해 생성된 JSON 파일을 다운로드할 수 있는 유연성도 제공합니다. 따라서, 직접 JSON 파일을 수정하지 않고도 관리 앱을 통해 손쉽게 맞춤설정을 할 수 있습니다.

In [6]:
## 환경설정
# !pip install -qU ragas langchain langchain-community langchain-openai langchain-chroma langchain-text-splitters pypdf rapidfuzz langgraph gdown chromadb langchain-huggingface sentence-transformers -q

In [7]:
# !pip install ragas

In [9]:
import os
from dotenv import load_dotenv

load_dotenv()
# 필요한 라이브러리 임포트
import os
import pandas as pd
from pprint import pprint
# LangChain 관련 라이브러리
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
# RAGAS 관련 라이브러리
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.testset.persona import Persona
from ragas.testset import TestsetGenerator
from ragas import EvaluationDataset, evaluate
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness

## 이미 생성된 합성 데이터셋 생성

In [10]:
import pandas as pd

# 같은 폴더(현재 작업 디렉토리)에 저장했다면
dataset_df = pd.read_csv("./dataset.csv")
print(dataset_df.shape)
display(dataset_df)

(20, 3)

,user_input,reference_contexts,reference
0,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 무엇인가요?,사용자가 다음 작업을 수행할 수 있게 해주는 Analytics Hub 게시자 역할(...,"Analytics Hub 게시자 역할은 목록을 생성, 업데이트, 삭제하고 목록에 I..."
1,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 어떻게 해...,BigQuery Studio 저장된 쿼리에 공개 액세스 권한이 부여되지 않도록 하려...,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 프로젝트에...
2,calendarId에 primary 키워드를 사용하면 어떤 캘린더에 접근할 수 있나요?,현재 로그인한 사용자의 기본 캘린더에 액세스하려면 'primary' 키워드를 사용하세요.,calendarId에 primary 키워드를 사용하면 현재 로그인한 사용자의 기본 ...
3,Google Drive API v3의 서비스 엔드포인트가 궁금해,"이 서비스에는 다음 서비스 엔드포인트가 포함되고, 그 아래의 모든 URI가 이 서비...",Google Drive API v3의 서비스 엔드포인트는 https://www.go...
4,files.create 메서드의 최대 파일 크기와 허용되는 미디어 MIME 유형은 ...,"최대 파일 크기: 5,120GB\r\n허용되는 미디어 MIME 유형: */*\r\n...","files.create 메서드의 최대 파일 크기는 5,120GB입니다. 허용되는 미..."
5,Firebase scrypt 해시 비밀번호를 사용한 사용자 가져오는 방법은?,기본적으로 Firebase는 scrypt 해싱 알고리즘의 수정된 Firebase 버...,"Firebase scrypt 해시 비밀번호를 사용한 사용자를 가져오려면, 먼저 Fi..."
6,커스텀 인증 시스템으로 Firebase에 인증하려면 어떻게 해야 하나요?,Firebase 인증에 맞춤 인증 시스템을 통합할 수 있습니다. 사용자가 정상적으로...,"커스텀 인증 시스템으로 Firebase에 인증하려면, 먼저 인증 서버에서 사용자의 ..."
7,"Firestore에서 맵 필드에 대한 단일 필드 색인 예외를 설정하면, 하위 필드들...",맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드에서 해당 설정을 상속합니다...,"네, Firestore에서 맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드..."
8,Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?,"Uses RFC 3339, where generated output will alw...",Firebase의 updateTime 필드에는 RFC 3339 시간 형식이 사용됩니...
9,Firefox 58 환경에서 Gmail의 AMP 렌더링 기능이 호환되나요?,브라우저 최소 버전\r\nChrome 69\r\nEdge 지원되지 않음\r\nFir...,"네, Firefox 58 환경에서는 Gmail의 AMP 렌더링 기능이 호환됩니다. ..."
10,Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 필요해?,DKIM 또는 SPF 인증 자체 테스트에는 여전히 필요합니다.,"네, Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 여전히 필요합니다."
11,"HTML 헤더에 스크립트 태그를 넣을 수 없을 때, 이메일 본문에 코드를 삽입하는 ...",이메일 구성 방식에 따라 이메일 본문의 할인/제품을 담당하는 시스템은 HTML 헤더...,"HTML 헤더에 스크립트 태그를 넣을 수 없는 경우, 이메일 본문에 스크립트 태그의..."
12,OAuth에서 승인 사용자 인증 정보 만드는 방법 순서대로 알려주세요.,1. 클라이언트 만들기를 클릭합니다. 2. TV 및 입력 제한 기기 애플리케이션 유...,"OAuth에서 승인 사용자 인증 정보를 만드는 방법은 다음과 같습니다. 먼저, '클..."
13,Google의 계정 간 보안 서비스를 사용하는데 디코딩된 보안 이벤트 토큰의 eve...,events 클레임에는 토큰이 나타내는 보안 이벤트에 관한 정보가 포함됩니다. 이 ...,디코딩된 보안 이벤트 토큰의 events 클레임에는 토큰이 나타내는 보안 이벤트에 ...
14,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...,또한 구성 파일이 있는 경우 파일에 다음 섹션을 직접 추가할 수 있습니다.\r\n\...,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...
15,"GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?","(0, 0) is the center of the map.","(0, 0)은 GMSMapPoint 좌표계에서 지도의 중심을 의미합니다."
16,People API의 RequestMask 필드에 무엇을 입력해야 하나요?,지원 중단된 서비스입니다.,지원 중단되었습니다. 대신 personFields를 사용해 주세요.
17,People API에 요청을 보내는 Python 스크립트를 어떻게 실행하고 구성해야...,Python용 Google 클라이언트 라이브러리를 설치합니다.\r\npip inst...,People API에 요청을 보내는 Python 스크립트를 실행하고 구성하려면 다음...
18,Google Sheets의 SERIAL_NUMBER 형식으로 1900년 2월 1일 ...,"날짜, 시간, 날짜/시간, 기간 필드를 Lotus 1-2-3에서 대중화한 '일련번호...",Google Sheets의 SERIAL_NUMBER 형식에서 1900년 2월 1일 ...
19,YouTube Data API를 사용하는 프로젝트의 기본 할당량은 얼마인가요?,"YouTube Data API를 사용 설정한 프로젝트의 기본 할당량은 일일 10,0...","YouTube Data API를 사용하는 프로젝트의 기본 할당량은 일일 10,000..."

In [11]:

## 02.RAG 체인 구성

import pandas as pd
from datasets import Dataset
import uuid
import time


evaluated_dataset = []

for _, row in dataset_df.iterrows():
    time.sleep(3)
    query = row.user_input  # 사용자 입력 - 합성 데이터셋에서 가져옴

    # run_langraph 함수 호출
    rag_result = run_langraph(query,'1', None)

    evaluated_dataset.append(
        {
            "user_input": query,
            "retrieved_contexts": [doc for doc in rag_result["search_results"]] + [doc for doc in rag_result['pseudo_doc_text_results']] + [doc for doc in rag_result['pseudo_doc_qa_results']],
            "response": rag_result["answer"],
            "reference": row['reference']
        }
    )

print("평가 데이터셋 준비 완료")

# RAGAS 평가 데이터셋 생성
ragas_evaluated_dataset = Dataset.from_list(evaluated_dataset)
# csv 데이터 저장
# ragas_evaluated_dataset.to_pandas().to_csv('ragas_evaluated_dataset_hybrid4.csv', index=False)
ragas_evaluated_dataset.to_pandas().info()

run_langraph 호출 - 입력: Analytics Hub 게시자와 목록 관리자 역할의 차이점은 무엇인가요?, 이미지: False
analyze_image 호출됨 - 이미지 존재: False
[tool_based_search_node] 실행 - queries=['Analytics Hub에서 게시자와 목록 관리자 역할의 차이점은 무엇인가요?', 'What is the difference between the publisher and list manager roles in Analytics Hub?']
[vector_search_tool] 검색 실행 - query='Analytics Hub에서 게시자와 목록 관리자 역할의 차이점은 무엇인가요?', filters={'tags': {'$in': ['bigquery']}}
[tool_based_search_node] 전달 인자: ['데이터 교환을 생성, 업데이트, 삭제합니다.\n목록을 생성, 업데이트, 삭제, 공유\nAnalytics Hub 관리자, 목록 관리자, 게시자, 구독자, 뷰어를 관리합니다.\n이 역할을 가진 사용자는 관리자라고 합니다.\nAnalytics Hub 게시자 및 목록 관리자 역할\nSharing은 목록을 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko]할 수 있도록 프로젝트, 데이터 교환 또는 목록에 부여할 수 있는 다음과 같은 사전 정의된 역할을 제공합니다.\n사용자가 다음 작업을 수행할 수 있게 해주는 Analytics Hub 게시자 역할(roles/analyticshub.publisher)\n목록 생성, 업데이트, 삭제\n목록에 IAM 정책 설정 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#grant-role-listing]\n이 역할을 가진 사용자를 게시자라고 합니다.\n사용자가 다음 작업을 수행할 수 있게 해주는 Analytics Hub 목록 관리자 역할(roles/analyticshub.listingAdmin)\n목록 업데이트 및 삭제\n목록에 IAM 정책 설정 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#grant-role-listing]\nAnalytics Hub 구독자 및 뷰어 역할\nSharing은 목록을 보고 구독 [https://cloud.google.com/bigquery/docs/analytics-hub-view-subscribe-listings?hl=ko]할 수 있도록 프로젝트, 데이터 교환 또는 목록에 부여할 수 있는 다음과 같은 사전 정의된 역할을 제공합니다.\n사용자가 목록을 보고 구독할 수 있게 해주는 Analytics Hub 구독자 역할(roles/analyticshub.subscriber)\n이 역할을 가진 사용자는 구독자라고 합니다.\n사용자가 목록 및 데이터 교환의 권한을 볼 수 있게 해주는 Analytics Hub 뷰어 역할(roles/analyticshub.viewer)\n이 역할을 가진 사용자를 뷰어라고 합니다.\nAnalytics Hub 구독 소유자 역할', 'Analytics Hub 관리자 역할을 사용하면 여러 데이터 교환을 만들고 공유 작업을 수행하는 다른 사용자를 관리할 수 있습니다.\n목록\n목록은 게시자가 데이터 교환에 나열하는 공유 리소스를 참조합니다. 게시자는 목록을 만들고 리소스 설명, 실행할 샘플 쿼리 또는 샘플 메시지 데이터, 관련 문서 링크, 구독자가 공유 리소스를 사용하는 데 도움이 되는 추가 정보를 지정할 수 있습니다. 목록을 만들 때 기본 연락처 이메일, 제공자 이름 및 연락처, 게시자 이름 및 연락처를 할당할 수 있습니다. 기본 연락처 이메일은 사용자가 데이터 교환에 관한 질문이나 우려사항이 있을 때 목록 소유자에게 연락할 수 있는 방법을 제공합니다. 제공자 이름과 연락처는 원래 목록의 데이터를 제공한 기관의 정보입니다. 이 정보는 선택사항입니다. 게시자 이름과 연락처는 BigQuery Sharing에 사용할 데이터를 게시한 기관입니다. 이 정보는 선택사항입니다. 자세한 내용은 목록 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko]를 참조하세요.\n목록은 목록에 설정된 Identity and Access Management(IAM) 정책과 목록을 포함하는 데이터 교환의 유형에 따라 다음 두 가지 유형 중 하나일 수 있습니다.\n공개 목록. 모든 Google Cloud 사용자(allAuthenticatedUsers) [https://cloud.google.com/iam/docs/principals-overview?hl=ko#all-authenticated-users]와 공유됩니다. 공개 데이터 교환의 목록은 공개 목록입니다. 이 목록은 무료 공개 리소스 또는 상용 리소스의 참조일 수 있습니다. 목록이 상용 리소스인 경우 구독자는 데이터 제공업체에 직접 목록에 대한 액세스를 요청하거나 Google Cloud Marketplace 통합 상용 목록 [https://cloud.google.com/bigquery/docs/analytics-hub-cloud-marketplace?hl=ko]을 탐색하고 구매할 수 있습니다.\n비공개 목록. 개인 또는 그룹과 직접 공유됩니다. 예를 들어 비공개 목록은 조직의 다른 내부 팀과 공유하는 마케팅 측정항목 데이터 세트를 참조할 수 있습니다.\n구독자 워크플로\n다음 다이어그램은 구독자가 공유 리소스와 상호작용하는 방식을 설명합니다.', '이 관리자는 다음 작업을 수행할 수 있습니다.\n조직의 예측 프로젝트에서 데이터 교환을 생성, 업데이트, 삭제, 공유합니다.\nAnalytics Hub 관리자 역할이 있는 다른 관리자를 관리합니다.\n조직 직원에게 Analytics Hub 게시자 역할을 부여하여 게시자를 관리합니다. 일부 직원의 경우에는 목록을 업데이트, 삭제, 공유할 수 있지만 만들 수는 없도록 하려면 Analytics Hub 목록 관리자 역할을 부여하면 됩니다.\n모든 공급업체로 구성된 Google 그룹에 Analytics Hub 구독자 역할을 부여하여 구독자를 관리합니다. 일부 공급업체에게 사용 가능한 교환 및 목록에 대한 보기 액세스 권한만 부여하려면 Analytics Hub 뷰어 역할을 부여하면 됩니다. 이러한 공급업체는 목록을 구독할 수 없습니다.\n자세한 내용은 데이터 교환 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-exchanges?hl=ko]를 참조하세요.\n게시자\n게시자는 예측 프로젝트 또는 다른 프로젝트에서 데이터 세트에 대해 다음 목록을 만듭니다.\n목록 A: 수요 예측 데이터 세트 1\n목록 B: 수요 예측 데이터 세트 2\n목록 C: 수요 예측 데이터 세트 3\n데이터 제공업체는 공유 데이터 세트에 대해 사용량 측정항목을 추적 [https://cloud.google.com/bigquery/docs/analytics-hub-monitor-listings?hl=ko#use-analytics-hub]할 수 있습니다. 사용량 측정항목에는 다음 세부정보가 포함됩니다.\n공유 데이터 세트에 대해 실행되는 작업\n구독자 프로젝트 및 조직의 공유 데이터 세트 소비 세부정보\n작업에서 처리한 행 및 바이트 수\n자세한 내용은 목록 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko]를 참조하세요.\n구독자\n구독자는 데이터 교환에서 액세스할 수 있는 목록을 탐색할 수 있습니다. 또한 연결된 데이터 세트를 만들어 이러한 목록을 구독하고 프로젝트에 데이터 세트를 추가할 수 있습니다. 공급업체는 연결된 데이터 세트에서 쿼리를 실행하고 실시간으로 결과를 검색할 수 있습니다.', '다음 필드에 이메일 주소를 입력하여 Analytics Hub 사용자 역할을 부여합니다.\n\n\n관리자: 이러한 사용자에게는 Analytics Hub 관리자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-admin-role]이 할당됩니다.\n게시자: 이러한 사용자에게는 Analytics Hub 게시자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-publisher-role]이 할당됩니다. 게시자가 수행할 수 있는 작업에 대한 자세한 내용은 목록 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko]를 참조하세요.\n구독자: 이러한 사용자에게는 Analytics Hub 구독자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-subscriber-role]이 할당됩니다. 구독자가 수행할 수 있는 작업에 대한 자세한 내용은 목록 보기 및 구독 [https://cloud.google.com/bigquery/docs/analytics-hub-view-subscribe-listings?hl=ko]을 참조하세요.\n뷰어: 이 사용자에게는 Analytics Hub 뷰어 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-subscriber-role]이 할당됩니다.\n뷰어는 목록을 볼 수 있습니다 [https://cloud.google.com/bigquery/docs/analytics-hub-view-subscribe-listings?hl=ko#discover-listings].\n\n공개 검색 가능 여부가 사용 설정된 경우 Analytics Hub 뷰어 역할(roles/analyticshub.viewer)을 allUsers 또는 allAuthenticatedUsers에 부여합니다.\n\n\n권한을 저장하려면 권한 설정을 클릭합니다.\n\n데이터 교환에 대한 권한을 설정하지 않은 경우 건너뛰기를 클릭합니다.', '공개 링크 복사를 클릭하여 인증되지 않은 목록 URL을 생성합니다. 이 목록에서 allUsers에 Analytics Hub 뷰어 역할(roles/analyticshub.viewer)을 부여해야 합니다.\n목록 관리자 만들기\n사용자가 목록을 관리할 수 있도록 하려면 공유 목록 관리자를 만들어야 합니다. 목록 관리자를 만들려면 목록 수준에서 Analytics Hub 게시자 또는 Analytics Hub 목록 관리자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-publisher-role]을 사용자에게 부여해야 합니다. 목록에 이러한 역할을 부여하는 방법에 대한 상세 설명은 목록에 역할 부여 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#grant-role-listing]를 참조하세요.\n정기 결제 모두 보기\n현재 등록정보에 대한 모든 구독을 보려면 다음 옵션 중 하나를 선택합니다.\n--- 탭: 콘솔 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko#%EC%BD%98%EC%86%94] ---\n공유 (Analytics Hub) 페이지로 이동합니다.', 'analyticshub.listings.list\n소유자 [https://cloud.google.com/iam/docs/roles-overview?hl=ko#basic](roles/owner)\n편집자 [https://cloud.google.com/iam/docs/roles-overview?hl=ko#basic](roles/editor)\n뷰어 [https://cloud.google.com/iam/docs/roles-overview?hl=ko#basic] (roles/viewer)\nAnalytics Hub 관리자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.admin](roles/analyticshub.admin)\nAnalytics Hub 목록 관리자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.listingAdmin](roles/analyticshub.listingAdmin)\nAnalytics Hub 게시자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.publisher](roles/analyticshub.publisher)\nAnalytics Hub 구독자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.subscriber](roles/analyticshub.subscriber)\nAnalytics Hub 구독 소유자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.subscriptionOwner](roles/analyticshub.subscriptionOwner)\nAnalytics Hub 뷰어 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.viewer](roles/analyticshub.viewer)', 'gcloud services enable analyticshub.googleapis.com\n필수 권한\n목록 및 구독을 관리하려면 다음 Analytics Hub 역할 중 하나가 있어야 합니다.\nAnalytics Hub 게시자 역할(roles/analyticshub.publisher) - 목록에 IAM 정책을 생성, 업데이트, 삭제, 설정할 수 있습니다.\nAnalytics Hub 목록 관리자 역할(roles/analyticshub.listingAdmin) - 목록에 IAM 정책을 업데이트, 삭제, 설정할 수 있습니다.\nAnalytics Hub 관리자 역할(roles/analyticshub.Admin) - 데이터 교환의 모든 목록에서 IAM 정책을 생성, 업데이트, 삭제, 설정할 수 있습니다.\n자세한 내용은 Analytics Hub 사용자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#user_roles]을 참조하세요. 다른 사용자에게 이러한 역할을 부여하는 방법을 알아보려면 목록 관리자 만들기 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko#create-listing-administrator]를 참조하세요.\n또한 목록을 만들려면 목록을 만들 데이터 세트에 대한 bigquery.datasets.get 및 bigquery.datasets.update 권한도 있어야 합니다. 다음 BigQuery 사전 정의된 역할 [https://cloud.google.com/bigquery/docs/access-control?hl=ko#bigquery]에 bigquery.datasets.update 권한이 포함되어 있습니다.\nBigQuery 데이터 소유자 역할(roles/bigquery.dataOwner)\nBigQuery 관리자 역할(roles/bigquery.admin)', '요청 본문에 목록 세부정보를 제공합니다. 요청이 성공하면 응답 본문에 목록 세부정보가 포함됩니다.\nAnalytics Hub 관리자 만들기\n데이터 교환을 관리하려면 Analytics Hub 관리자를 만들어야 합니다. 교환 관리자를 만들려면 프로젝트 또는 데이터 교환 수준에서 사용자에게 Analytics Hub 관리자 역할(roles/analyticshub.admin) [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-admin-role]을 부여해야 합니다.\n관리자가 프로젝트의 모든 데이터 교환을 관리하게 하려면 해당 프로젝트에 Analytics Hub 관리자 역할을 부여합니다 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#grant-role-project]. 관리자가 특정 데이터 교환을 관리하도록 하려면 해당 데이터 교환에 대한 Analytics Hub 관리자 역할을 부여합니다 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#grant-role-data-exchange].\n데이터 교환 공개\n기본적으로 데이터 교환은 비공개이며 해당 교환에 액세스할 수 있는 사용자 또는 그룹만 목록을 보거나 구독할 수 있습니다. 하지만 데이터 교환을 공개로 설정할 수 있습니다. Google Cloud 사용자(allAuthenticatedUsers) [https://cloud.google.com/iam/docs/principals-overview?hl=ko#all-authenticated-users]가 공개 데이터 교환의 목록을 탐색하고 구독할 수 있습니다.\n데이터 교환을 공개로 설정하려면 다음 단계를 따르세요.']
[vector_search_tool] 검색 실행 - query='What is the difference between the publisher and list manager roles in Analytics Hub?', filters={'tags': {'$in': ['bigquery']}}
[tool_based_search_node] 전달 인자: ['데이터 교환을 생성, 업데이트, 삭제합니다.\n목록을 생성, 업데이트, 삭제, 공유\nAnalytics Hub 관리자, 목록 관리자, 게시자, 구독자, 뷰어를 관리합니다.\n이 역할을 가진 사용자는 관리자라고 합니다.\nAnalytics Hub 게시자 및 목록 관리자 역할\nSharing은 목록을 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko]할 수 있도록 프로젝트, 데이터 교환 또는 목록에 부여할 수 있는 다음과 같은 사전 정의된 역할을 제공합니다.\n사용자가 다음 작업을 수행할 수 있게 해주는 Analytics Hub 게시자 역할(roles/analyticshub.publisher)\n목록 생성, 업데이트, 삭제\n목록에 IAM 정책 설정 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#grant-role-listing]\n이 역할을 가진 사용자를 게시자라고 합니다.\n사용자가 다음 작업을 수행할 수 있게 해주는 Analytics Hub 목록 관리자 역할(roles/analyticshub.listingAdmin)\n목록 업데이트 및 삭제\n목록에 IAM 정책 설정 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#grant-role-listing]\nAnalytics Hub 구독자 및 뷰어 역할\nSharing은 목록을 보고 구독 [https://cloud.google.com/bigquery/docs/analytics-hub-view-subscribe-listings?hl=ko]할 수 있도록 프로젝트, 데이터 교환 또는 목록에 부여할 수 있는 다음과 같은 사전 정의된 역할을 제공합니다.\n사용자가 목록을 보고 구독할 수 있게 해주는 Analytics Hub 구독자 역할(roles/analyticshub.subscriber)\n이 역할을 가진 사용자는 구독자라고 합니다.\n사용자가 목록 및 데이터 교환의 권한을 볼 수 있게 해주는 Analytics Hub 뷰어 역할(roles/analyticshub.viewer)\n이 역할을 가진 사용자를 뷰어라고 합니다.\nAnalytics Hub 구독 소유자 역할', 'analyticshub.listings.list\n소유자 [https://cloud.google.com/iam/docs/roles-overview?hl=ko#basic](roles/owner)\n편집자 [https://cloud.google.com/iam/docs/roles-overview?hl=ko#basic](roles/editor)\n뷰어 [https://cloud.google.com/iam/docs/roles-overview?hl=ko#basic] (roles/viewer)\nAnalytics Hub 관리자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.admin](roles/analyticshub.admin)\nAnalytics Hub 목록 관리자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.listingAdmin](roles/analyticshub.listingAdmin)\nAnalytics Hub 게시자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.publisher](roles/analyticshub.publisher)\nAnalytics Hub 구독자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.subscriber](roles/analyticshub.subscriber)\nAnalytics Hub 구독 소유자 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.subscriptionOwner](roles/analyticshub.subscriptionOwner)\nAnalytics Hub 뷰어 [https://cloud.google.com/iam/docs/roles-permissions/analyticshub?hl=ko#analyticshub.viewer](roles/analyticshub.viewer)', 'Analytics Hub 관리자 역할을 사용하면 여러 데이터 교환을 만들고 공유 작업을 수행하는 다른 사용자를 관리할 수 있습니다.\n목록\n목록은 게시자가 데이터 교환에 나열하는 공유 리소스를 참조합니다. 게시자는 목록을 만들고 리소스 설명, 실행할 샘플 쿼리 또는 샘플 메시지 데이터, 관련 문서 링크, 구독자가 공유 리소스를 사용하는 데 도움이 되는 추가 정보를 지정할 수 있습니다. 목록을 만들 때 기본 연락처 이메일, 제공자 이름 및 연락처, 게시자 이름 및 연락처를 할당할 수 있습니다. 기본 연락처 이메일은 사용자가 데이터 교환에 관한 질문이나 우려사항이 있을 때 목록 소유자에게 연락할 수 있는 방법을 제공합니다. 제공자 이름과 연락처는 원래 목록의 데이터를 제공한 기관의 정보입니다. 이 정보는 선택사항입니다. 게시자 이름과 연락처는 BigQuery Sharing에 사용할 데이터를 게시한 기관입니다. 이 정보는 선택사항입니다. 자세한 내용은 목록 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko]를 참조하세요.\n목록은 목록에 설정된 Identity and Access Management(IAM) 정책과 목록을 포함하는 데이터 교환의 유형에 따라 다음 두 가지 유형 중 하나일 수 있습니다.\n공개 목록. 모든 Google Cloud 사용자(allAuthenticatedUsers) [https://cloud.google.com/iam/docs/principals-overview?hl=ko#all-authenticated-users]와 공유됩니다. 공개 데이터 교환의 목록은 공개 목록입니다. 이 목록은 무료 공개 리소스 또는 상용 리소스의 참조일 수 있습니다. 목록이 상용 리소스인 경우 구독자는 데이터 제공업체에 직접 목록에 대한 액세스를 요청하거나 Google Cloud Marketplace 통합 상용 목록 [https://cloud.google.com/bigquery/docs/analytics-hub-cloud-marketplace?hl=ko]을 탐색하고 구매할 수 있습니다.\n비공개 목록. 개인 또는 그룹과 직접 공유됩니다. 예를 들어 비공개 목록은 조직의 다른 내부 팀과 공유하는 마케팅 측정항목 데이터 세트를 참조할 수 있습니다.\n구독자 워크플로\n다음 다이어그램은 구독자가 공유 리소스와 상호작용하는 방식을 설명합니다.', '이 관리자는 다음 작업을 수행할 수 있습니다.\n조직의 예측 프로젝트에서 데이터 교환을 생성, 업데이트, 삭제, 공유합니다.\nAnalytics Hub 관리자 역할이 있는 다른 관리자를 관리합니다.\n조직 직원에게 Analytics Hub 게시자 역할을 부여하여 게시자를 관리합니다. 일부 직원의 경우에는 목록을 업데이트, 삭제, 공유할 수 있지만 만들 수는 없도록 하려면 Analytics Hub 목록 관리자 역할을 부여하면 됩니다.\n모든 공급업체로 구성된 Google 그룹에 Analytics Hub 구독자 역할을 부여하여 구독자를 관리합니다. 일부 공급업체에게 사용 가능한 교환 및 목록에 대한 보기 액세스 권한만 부여하려면 Analytics Hub 뷰어 역할을 부여하면 됩니다. 이러한 공급업체는 목록을 구독할 수 없습니다.\n자세한 내용은 데이터 교환 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-exchanges?hl=ko]를 참조하세요.\n게시자\n게시자는 예측 프로젝트 또는 다른 프로젝트에서 데이터 세트에 대해 다음 목록을 만듭니다.\n목록 A: 수요 예측 데이터 세트 1\n목록 B: 수요 예측 데이터 세트 2\n목록 C: 수요 예측 데이터 세트 3\n데이터 제공업체는 공유 데이터 세트에 대해 사용량 측정항목을 추적 [https://cloud.google.com/bigquery/docs/analytics-hub-monitor-listings?hl=ko#use-analytics-hub]할 수 있습니다. 사용량 측정항목에는 다음 세부정보가 포함됩니다.\n공유 데이터 세트에 대해 실행되는 작업\n구독자 프로젝트 및 조직의 공유 데이터 세트 소비 세부정보\n작업에서 처리한 행 및 바이트 수\n자세한 내용은 목록 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko]를 참조하세요.\n구독자\n구독자는 데이터 교환에서 액세스할 수 있는 목록을 탐색할 수 있습니다. 또한 연결된 데이터 세트를 만들어 이러한 목록을 구독하고 프로젝트에 데이터 세트를 추가할 수 있습니다. 공급업체는 연결된 데이터 세트에서 쿼리를 실행하고 실시간으로 결과를 검색할 수 있습니다.', '다음 필드에 이메일 주소를 입력하여 Analytics Hub 사용자 역할을 부여합니다.\n\n\n관리자: 이러한 사용자에게는 Analytics Hub 관리자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-admin-role]이 할당됩니다.\n게시자: 이러한 사용자에게는 Analytics Hub 게시자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-publisher-role]이 할당됩니다. 게시자가 수행할 수 있는 작업에 대한 자세한 내용은 목록 관리 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko]를 참조하세요.\n구독자: 이러한 사용자에게는 Analytics Hub 구독자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-subscriber-role]이 할당됩니다. 구독자가 수행할 수 있는 작업에 대한 자세한 내용은 목록 보기 및 구독 [https://cloud.google.com/bigquery/docs/analytics-hub-view-subscribe-listings?hl=ko]을 참조하세요.\n뷰어: 이 사용자에게는 Analytics Hub 뷰어 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-subscriber-role]이 할당됩니다.\n뷰어는 목록을 볼 수 있습니다 [https://cloud.google.com/bigquery/docs/analytics-hub-view-subscribe-listings?hl=ko#discover-listings].\n\n공개 검색 가능 여부가 사용 설정된 경우 Analytics Hub 뷰어 역할(roles/analyticshub.viewer)을 allUsers 또는 allAuthenticatedUsers에 부여합니다.\n\n\n권한을 저장하려면 권한 설정을 클릭합니다.\n\n데이터 교환에 대한 권한을 설정하지 않은 경우 건너뛰기를 클릭합니다.', '공개 링크 복사를 클릭하여 인증되지 않은 목록 URL을 생성합니다. 이 목록에서 allUsers에 Analytics Hub 뷰어 역할(roles/analyticshub.viewer)을 부여해야 합니다.\n목록 관리자 만들기\n사용자가 목록을 관리할 수 있도록 하려면 공유 목록 관리자를 만들어야 합니다. 목록 관리자를 만들려면 목록 수준에서 Analytics Hub 게시자 또는 Analytics Hub 목록 관리자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#ah-publisher-role]을 사용자에게 부여해야 합니다. 목록에 이러한 역할을 부여하는 방법에 대한 상세 설명은 목록에 역할 부여 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#grant-role-listing]를 참조하세요.\n정기 결제 모두 보기\n현재 등록정보에 대한 모든 구독을 보려면 다음 옵션 중 하나를 선택합니다.\n--- 탭: 콘솔 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko#%EC%BD%98%EC%86%94] ---\n공유 (Analytics Hub) 페이지로 이동합니다.', 'gcloud services enable analyticshub.googleapis.com\n필수 권한\n목록 및 구독을 관리하려면 다음 Analytics Hub 역할 중 하나가 있어야 합니다.\nAnalytics Hub 게시자 역할(roles/analyticshub.publisher) - 목록에 IAM 정책을 생성, 업데이트, 삭제, 설정할 수 있습니다.\nAnalytics Hub 목록 관리자 역할(roles/analyticshub.listingAdmin) - 목록에 IAM 정책을 업데이트, 삭제, 설정할 수 있습니다.\nAnalytics Hub 관리자 역할(roles/analyticshub.Admin) - 데이터 교환의 모든 목록에서 IAM 정책을 생성, 업데이트, 삭제, 설정할 수 있습니다.\n자세한 내용은 Analytics Hub 사용자 역할 [https://cloud.google.com/bigquery/docs/analytics-hub-grant-roles?hl=ko#user_roles]을 참조하세요. 다른 사용자에게 이러한 역할을 부여하는 방법을 알아보려면 목록 관리자 만들기 [https://cloud.google.com/bigquery/docs/analytics-hub-manage-listings?hl=ko#create-listing-administrator]를 참조하세요.\n또한 목록을 만들려면 목록을 만들 데이터 세트에 대한 bigquery.datasets.get 및 bigquery.datasets.update 권한도 있어야 합니다. 다음 BigQuery 사전 정의된 역할 [https://cloud.google.com/bigquery/docs/access-control?hl=ko#bigquery]에 bigquery.datasets.update 권한이 포함되어 있습니다.\nBigQuery 데이터 소유자 역할(roles/bigquery.dataOwner)\nBigQuery 관리자 역할(roles/bigquery.admin)', 'analyticshub.listings.update\nanalyticshub.listings.viewSubscriptions\nanalyticshub.subscriptions.*\nresourcemanager.projects.get\nresourcemanager.projects.list\nAnalytics Hub Listing Admin\n(roles/analyticshub.listingAdmin)\nGrants full control over the Listing, including updating, deleting and setting ACLs\nanalyticshub.dataExchanges.get\nanalyticshub.dataExchanges.getIamPolicy\nanalyticshub.dataExchanges.list\nanalyticshub.listings.delete\nanalyticshub.listings.get\nanalyticshub.listings.getIamPolicy\nanalyticshub.listings.list\nanalyticshub.listings.setIamPolicy\nanalyticshub.listings.update\nanalyticshub.listings.viewSubscriptions\nresourcemanager.projects.get\nresourcemanager.projects.list\nAnalytics Hub Publisher\n(roles/analyticshub.publisher)\nCan publish to Data Exchanges thus creating Listings\nanalyticshub.dataExchanges.get\nanalyticshub.dataExchanges.getIamPolicy\nanalyticshub.dataExchanges.list\nanalyticshub.listings.create\nanalyticshub.listings.get\nanalyticshub.listings.getIamPolicy\nanalyticshub.listings.list\nresourcemanager.projects.get\nresourcemanager.projects.list\nAnalytics Hub Subscriber\n(roles/analyticshub.subscriber)\nCan browse Data Exchanges and subscribe to Listings']
[qa_tool_based_search_node] 실행 - queries=['Analytics Hub에서 게시자와 목록 관리자 역할의 차이점은 무엇인가요?', 'What is the difference between the publisher and list manager roles in Analytics Hub?']
[qa_vector_search_tool] 검색 실행 - query='Analytics Hub에서 게시자와 목록 관리자 역할의 차이점은 무엇인가요?', filters={'tags': {'$in': ['bigquery']}}

In [16]:
### RAGAS 평가 실행

# LLM 래퍼 생성
evaluator_llm = ChatOpenAI(model="gpt-4.1-mini", temperature=0)
evaluator_llm = LangchainLLMWrapper(evaluator_llm)

# 평가 메트릭 정의
metrics = [
    LLMContextRecall(),  # 검색된 컨텍스트의 회수율
    Faithfulness(),  # 생성된 답변의 충실도
    FactualCorrectness()  # 사실적 정확성
]
# 평가 실행

result = evaluate(
    dataset=ragas_evaluated_dataset,
    metrics=metrics,
    llm=evaluator_llm,
)

print(result)
# 결과를 DataFrame으로 변환
result_df = result.to_pandas()

# 결과 저장
# result_df.to_csv('ragas_evaluation_result_hybrid4.csv', index=False)

display(result_df.head())
result_df[['context_recall', 'faithfulness', 'factual_correctness(mode=f1)']].describe()

Evaluating:   0%|          | 0/60 [00:00<?, ?it/s]

{'context_recall': 0.9500, 'faithfulness': 0.9348, 'factual_correctness(mode=f1)': 0.6730}

,user_input,retrieved_contexts,response,reference,context_recall,faithfulness,factual_correctness(mode=f1)
0,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 무엇인가요?,"[데이터 교환을 생성, 업데이트, 삭제합니다.\n목록을 생성, 업데이트, 삭제, 공...",Analytics Hub 게시자 역할과 목록 관리자 역할의 차이점은 다음과 같습니다...,"Analytics Hub 게시자 역할은 목록을 생성, 업데이트, 삭제하고 목록에 I...",1.0,1.0,0.93
1,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 어떻게 해...,[탐색기 창에서 프로젝트와 쿼리 폴더를 펼치고 필요한 경우 공유 쿼리 폴더를 펼칩니...,BigQuery Studio 저장된 쿼리에 대한 공개 액세스를 방지하려면 프로젝트에...,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 프로젝트에...,1.0,1.0,0.91
2,calendarId에 primary 키워드를 사용하면 어떤 캘린더에 접근할 수 있나요?,[이 페이지는 Cloud Translation API [https://cloud.g...,현재 로그인한 사용자의 기본 캘린더에 접근하기 위해서는 `primary` 키워드를 ...,calendarId에 primary 키워드를 사용하면 현재 로그인한 사용자의 기본 ...,1.0,1.0,0.67
3,Google Drive API v3의 서비스 엔드포인트가 궁금해,[https://www.googleapis.com/discovery/v1/apis/...,Google Drive API v3의 서비스 엔드포인트는 `https://www.g...,Google Drive API v3의 서비스 엔드포인트는 https://www.go...,1.0,1.0,0.67
4,files.create 메서드의 최대 파일 크기와 허용되는 미디어 MIME 유형은 ...,[이 페이지는 Cloud Translation API [https://cloud.g...,files.create 메서드를 사용하여 파일을 업로드할 때 지원되는 최대 파일 크...,"files.create 메서드의 최대 파일 크기는 5,120GB입니다. 허용되는 미...",1.0,1.0,0.86

       context_recall  faithfulness  factual_correctness(mode=f1)
count       20.000000     20.000000                     20.000000
mean         0.950000      0.934829                      0.673000
std          0.223607      0.135599                      0.272997
min          0.000000      0.555556                      0.000000
25%          1.000000      0.993590                      0.537500
50%          1.000000      1.000000                      0.710000
75%          1.000000      1.000000                      0.912500
max          1.000000      1.000000                      1.000000

In [17]:
display(result_df)

,user_input,retrieved_contexts,response,reference,context_recall,faithfulness,factual_correctness(mode=f1)
0,Analytics Hub 게시자와 목록 관리자 역할의 차이점은 무엇인가요?,"[데이터 교환을 생성, 업데이트, 삭제합니다.\n목록을 생성, 업데이트, 삭제, 공...",Analytics Hub 게시자 역할과 목록 관리자 역할의 차이점은 다음과 같습니다...,"Analytics Hub 게시자 역할은 목록을 생성, 업데이트, 삭제하고 목록에 I...",1.0,1.000000,0.93
1,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 어떻게 해...,[탐색기 창에서 프로젝트와 쿼리 폴더를 펼치고 필요한 경우 공유 쿼리 폴더를 펼칩니...,BigQuery Studio 저장된 쿼리에 대한 공개 액세스를 방지하려면 프로젝트에...,BigQuery Studio 저장된 쿼리에 공개 액세스 권한을 방지하려면 프로젝트에...,1.0,1.000000,0.91
2,calendarId에 primary 키워드를 사용하면 어떤 캘린더에 접근할 수 있나요?,[이 페이지는 Cloud Translation API [https://cloud.g...,현재 로그인한 사용자의 기본 캘린더에 접근하기 위해서는 `primary` 키워드를 ...,calendarId에 primary 키워드를 사용하면 현재 로그인한 사용자의 기본 ...,1.0,1.000000,0.67
3,Google Drive API v3의 서비스 엔드포인트가 궁금해,[https://www.googleapis.com/discovery/v1/apis/...,Google Drive API v3의 서비스 엔드포인트는 `https://www.g...,Google Drive API v3의 서비스 엔드포인트는 https://www.go...,1.0,1.000000,0.67
4,files.create 메서드의 최대 파일 크기와 허용되는 미디어 MIME 유형은 ...,[이 페이지는 Cloud Translation API [https://cloud.g...,files.create 메서드를 사용하여 파일을 업로드할 때 지원되는 최대 파일 크...,"files.create 메서드의 최대 파일 크기는 5,120GB입니다. 허용되는 미...",1.0,1.000000,0.86
5,Firebase scrypt 해시 비밀번호를 사용한 사용자 가져오는 방법은?,[Source URL: https://firebase.google.com/docs/...,Firebase scrypt 해시 비밀번호를 사용하여 사용자를 가져오는 방법은 다음...,"Firebase scrypt 해시 비밀번호를 사용한 사용자를 가져오려면, 먼저 Fi...",1.0,1.000000,0.76
6,커스텀 인증 시스템으로 Firebase에 인증하려면 어떻게 해야 하나요?,[Source URL: https://firebase.google.com/docs/...,Firebase에서 커스텀 인증 시스템을 사용하려면 다음과 같은 절차를 따르시면 됩...,"커스텀 인증 시스템으로 Firebase에 인증하려면, 먼저 인증 서버에서 사용자의 ...",1.0,1.000000,0.67
7,"Firestore에서 맵 필드에 대한 단일 필드 색인 예외를 설정하면, 하위 필드들...",[맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드에서 해당 설정을 상속합니...,"Firestore에서 맵 필드에 대한 단일 필드 색인 예외를 설정하면, 맵의 하위 ...","네, Firestore에서 맵 필드에 단일 필드 색인 예외를 만들면 맵의 하위 필드...",1.0,1.000000,0.57
8,Firebase의 updateTime 필드에 사용되는 시간 형식이 뭐야?,"[웹 버전 9\nimport { doc, setDoc, Timestamp } fro...",Firebase의 `updateTime` 필드는 RFC 3339 형식을 사용합니다....,Firebase의 updateTime 필드에는 RFC 3339 시간 형식이 사용됩니...,1.0,1.000000,0.92
9,Firefox 58 환경에서 Gmail의 AMP 렌더링 기능이 호환되나요?,[Source URL: https://developers.google.com/wor...,Firefox 58 환경에서는 Gmail의 AMP 렌더링 기능이 호환됩니다. 따라서...,"네, Firefox 58 환경에서는 Gmail의 AMP 렌더링 기능이 호환됩니다. ...",1.0,0.750000,0.33
10,Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 필요해?,[이메일이 SPF (Sender Policy Framework) 인증 [https:...,Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증은 여전히 필요합니다. 자...,"네, Gmail 자가 테스트를 할 때 DKIM 또는 SPF 인증이 여전히 필요합니다.",1.0,1.000000,0.80
11,"HTML 헤더에 스크립트 태그를 넣을 수 없을 때, 이메일 본문에 코드를 삽입하는 ...",[이 페이지는 Cloud Translation API [https://cloud.g...,"이메일 본문에 스크립트 태그를 삽입할 때, HTML 헤더에 스크립트 태그를 넣을 수...","HTML 헤더에 스크립트 태그를 넣을 수 없는 경우, 이메일 본문에 스크립트 태그의...",1.0,1.000000,0.75
12,OAuth에서 승인 사용자 인증 정보 만드는 방법 순서대로 알려주세요.,[사용 설정하려는 API를 선택한 다음 사용 설정 버튼을 클릭합니다.\nIf pro...,OAuth 2.0을 사용하여 Google API에 액세스하기 위해 승인 사용자 인증...,"OAuth에서 승인 사용자 인증 정보를 만드는 방법은 다음과 같습니다. 먼저, '클...",1.0,1.000000,0.55
13,Google의 계정 간 보안 서비스를 사용하는데 디코딩된 보안 이벤트 토큰의 eve...,[jti 클레임은 단일 보안 이벤트를 식별하는 문자열이며 스트림에 고유합니다. 이 ...,"Google의 계정 간 보안 서비스를 사용하는 경우, 디코딩된 보안 이벤트 토큰의 ...",디코딩된 보안 이벤트 토큰의 events 클레임에는 토큰이 나타내는 보안 이벤트에 ...,1.0,1.000000,0.94
14,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...,[assignment [https://developers.google.com/map...,3D 스토리텔링 솔루션의 '표지'를 구성하기 위해 `config.json` 파일에 ...,MAP 3D 스토리텔링의 '표지'를 구성하기 위해 config.json 파일에 직접...,1.0,0.750000,0.33
15,"GMSMapPoint의 좌표계에서 (0, 0)은 어떤 지점을 의미하나요?",[GMSProjection [https://developers.google.com/...,"죄송하지만, GMSMapPoint의 좌표계에서 (0, 0)이 어떤 지점을 의미하는지...","(0, 0)은 GMSMapPoint 좌표계에서 지도의 중심을 의미합니다.",0.0,0.666667,0.00
16,People API의 RequestMask 필드에 무엇을 입력해야 하나요?,[Source URL: https://developers.google.com/peo...,"People API의 RequestMask 필드는 더 이상 사용되지 않으며, 대신 ...",지원 중단되었습니다. 대신 personFields를 사용해 주세요.,1.0,1.000000,0.50
17,People API에 요청을 보내는 Python 스크립트를 어떻게 실행하고 구성해야...,[People API에 요청을 보내려면 먼저 Google에 클라이언트에 관해 알리고...,People API에 요청을 보내는 Python 스크립트를 실행하고 구성하는 방법은...,People API에 요청을 보내는 Python 스크립트를 실행하고 구성하려면 다음...,1.0,0.974359,0.30
18,Google Sheets의 SERIAL_NUMBER 형식으로 1900년 2월 1일 ...,[Source URL: https://developers.google.com/wor...,Google Sheets의 SERIAL_NUMBER 형식으로 1900년 2월 1일 ...,Google Sheets의 SERIAL_NUMBER 형식에서 1900년 2월 1일 ...,1.0,0.555556,1.00
19,YouTube Data API를 사용하는 프로젝트의 기본 할당량은 얼마인가요?,[YouTube에서 Shorts 동영상의 조회수를 집계하는 방식에 맞게 Data A...,"YouTube Data API를 사용하는 프로젝트의 기본 할당량은 일일 10,000...","YouTube Data API를 사용하는 프로젝트의 기본 할당량은 일일 10,000...",1.0,1.000000,1.00